Query formatted disks gptids after mass formatting to prevent race co…
truenas/middleware pull request #10269
Opened 2022-12-19 12:11 UTC by themylogin

2022-12-19 12:11 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-117470

2022-12-19 12:12 UTC, themylogin commented
time 0:30

2022-12-19 12:17 UTC, yocalebo requested changes
1. update docstring
2. `system.is_ha_capable` can be called outside the inner `format_disk` method and simply passed as another arg
3. call `len(disks)` outside inner `format_disk` method and pass it in as an arg too

2022-12-19 13:04 UTC, yocalebo commented on src/middlewared/middlewared/plugins/pool_/format_disks.py
> +        Format all disks, putting all ZFS partitions created  into their respective vdevs.
```suggestion
        Format all disks, putting all ZFS partitions created into their respective vdevs.
```

2023-01-10 15:42 UTC, yocalebo approved these changes
Confirmed on internal hardware that this works 😄

2023-01-10 15:43 UTC, merged