Use `$` for `admin` user zsh prompt
truenas/middleware pull request #10303
Opened 2022-12-28 12:03 UTC by themylogin

2022-12-28 12:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119618

2022-12-28 12:04 UTC, themylogin commented
time 0:30

2022-12-28 12:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119618

2022-12-29 13:05 UTC, anodos325 approved these changes

2022-12-29 13:07 UTC, yocalebo requested changes
How does this effect `admin` user since you're changing `/root/.zshrc` file?

2022-12-29 18:22 UTC, themylogin commented
@yocalebo `/home/admin` is a copy of `/root` https://github.com/truenas/middleware/blob/master/src/freenas/debian/rules#L25

2022-12-29 18:29 UTC, yocalebo approved these changes

2022-12-29 18:29 UTC, merged