Do not reset `/home/admin` permissions
truenas/middleware pull request #10309
Opened 2022-12-28 13:57 UTC by themylogin

2022-12-28 13:58 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119570

2022-12-28 14:37 UTC, anodos325 commented
Since these permissions are rather important, maybe add some tests to ensure that we don't have another regression.

2022-12-28 14:42 UTC, yocalebo requested changes
Agree, should be relatively easy to add tests to check perms and owner info for this dir

2022-12-29 11:45 UTC, yocalebo approved these changes
Great!

2022-12-29 12:42 UTC, merged