Add ALUA support for iSCSI in SCALE
truenas/middleware pull request #10428
Opened 2023-01-13 17:04 UTC by bmeagherix

2023-01-13 17:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119337

2023-02-06 13:02 UTC, yocalebo reviewed
Just some things I've noticed along the way.

2023-02-06 13:02 UTC, yocalebo commented on src/middlewared/middlewared/plugins/dlm.py
> +        if not os.path.isdir(KernelDlm.CLUSTER_DIR):
Or another way is to `import contextlib` and do something like
```
with contextlib.supporess(FileExistsError):
    for i in (blah):
        os.mkdir(i)
```

Up to you really 😄

2023-02-06 16:34 UTC, bmeagherix commented on src/middlewared/middlewared/plugins/dlm.py
> +        if not os.path.isdir(KernelDlm.CLUSTER_DIR):
FWIW, went with the contextlib suppress

2023-02-09 19:40 UTC, anodos325 commented on src/middlewared/middlewared/plugins/dlm.py
> +        with contextlib.suppress(FileExistsError):
Wouldn't you want to suppress the os.mkdir() call rather than the iterator?

2023-05-17 18:28 UTC, anodos325 commented on src/middlewared/middlewared/plugins/dlm.py
> +    # await middleware.call('failover.remote_on_connect', remote_status_event)
Should this be commented out?

2023-05-17 18:44 UTC, anodos325 commented on src/middlewared/middlewared/plugins/dlm.py
> +    async def add_node(self, nodeid):
I think it's okay to leave place-holder methods for future enhancements, but we probably need to note that it's a placeholder and raise a NonImplementedError at beginning of method

2023-05-17 18:48 UTC, anodos325 commented on src/middlewared/middlewared/plugins/dlm_/kernel.py
> +        raise NotImplementedError('Not implemented')
Maybe explicitly state that IPv6 is not supported (clearer exception)

2023-05-17 19:11 UTC, anodos325 commented on src/middlewared/middlewared/plugins/dlm_/kernel.py
> +            os.rmdir(node_path)
Might want to double-check that this won't fail with ENOTEMPTY

2023-05-17 19:13 UTC, anodos325 commented on src/middlewared/middlewared/plugins/failover_/event.py
> +                    sleep(1)
need to decrement `timeout`

2023-05-17 20:04 UTC, anodos325 commented on src/middlewared/middlewared/service/service_mixin.py
> +    async def _service_change(self, service, verb, options={}):
I thing general convention would be `options=None` rather than an empty dict.

2023-05-17 20:14 UTC, anodos325 commented on src/middlewared/middlewared/service/system_service.py
> +    async def _update_service(self, old, new, verb=None, options={}):
ditto regarding `options=None`

2023-05-22 15:55 UTC, yocalebo requested changes
Overall looks good, I made a few notes and asked for a minor change in the etc generation portion of the code.

2023-05-22 15:56 UTC, yocalebo commented on src/middlewared/middlewared/etc_files/scst.conf.mako
> +    ha_capable = middleware.call_sync("system.is_ha_capable")
I shouldn't have said never. What I meant is that we have customers that buy an HA capable system that is only populated with the A controller and have plans to upgrade to HA in the future. (That's what we typically see, at least)

2023-05-22 16:41 UTC, yocalebo approved these changes
Fantastic!

2023-05-22 19:52 UTC, merged