Add guest agent channel in devices
truenas/middleware pull request #10443
Opened 2023-01-15 22:30 UTC by Qubad786

## Problem

With some guests proper shutdown cannot be initiated unless libvirt is able to communicate with the guest libvirt agent.

## Solution

Allow libvirt to interact with guest agent by opening a unix channel so that proper shutdown can be initiated in guests.

2023-01-15 22:31 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119681

2023-01-16 12:29 UTC, yocalebo approved these changes

2023-01-16 12:34 UTC, yocalebo requested changes
Seems like this broke a unit test.

2023-01-17 17:49 UTC, yocalebo approved these changes

2023-01-17 17:49 UTC, merged

2023-01-17 17:49 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-119681 is targeted to the following versions which have not received their corresponding PRs: 22.12.1

2023-01-17 18:08 UTC, Qubad786 commented
backport