dont add pmem devices to smartd.conf
truenas/middleware pull request #10523
Opened 2023-01-23 18:40 UTC by yocalebo

2023-01-23 18:40 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119983

2023-01-23 19:08 UTC, anodos325 approved these changes

2023-01-23 19:55 UTC, themylogin requested changes
* This is the method to list disks that support SMART self-testing (for scheduling self-test). It is not related to smartd.conf generation.
* nvme devices still do not support smart self-testing, don't remove that condition

2023-01-23 20:00 UTC, yocalebo commented
> * This is the method to list disks that support SMART self-testing (for scheduling self-test). It is not related to smartd.conf generation.
> * nvme devices still do not support smart self-testing, don't remove that condition

sigh, so complex when self-testing and monitoring smart attributes typically infer the other is true. Thanks for pointing out, I'll fix...

2023-01-24 15:39 UTC, themylogin approved these changes

2023-01-24 15:41 UTC, merged