Stop kubernetes/VPN services when moving system dataset
truenas/middleware pull request #10635
Opened 2023-02-02 17:04 UTC by sonicaj

This PR adds changes to restart k8s/vpn services when system dataset is being moved as otherwise it is potentially possible that the service in question is consuming the logging dataset.

2023-02-02 17:05 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120196

2023-02-02 17:58 UTC, anodos325 commented on src/middlewared/middlewared/plugins/sysdataset.py
> +                        restart.append(svc_to_check['name'])
You could probably simplify to:
```
restart.insert(svc_to_check.get('index', len(restart)), svc_to_check['name'])
```

2023-02-02 18:57 UTC, yocalebo requested changes
Please don't do this on master as I'm working on a PR locally to remove /var/log from system dataset so this won't be needed. You can keep the changes to 22.12.2 and 22.12.1

2023-02-03 06:22 UTC, sonicaj commented
backport

2023-02-03 06:23 UTC, closed without merging