Fix tests
truenas/middleware pull request #10669
Opened 2023-02-08 19:43 UTC by yocalebo

Changes introduced here https://github.com/truenas/middleware/pull/10655 exposed the fact that our tests were written with the assumption that sqlite didn't autoincrement columns on insert. Well...turns out it wasn't actually doing that which was breaking cloud-sync tasks so we fixed the autoincrement problem but then it broke these tests.

Fixes employed here:
1. update the global `tp['id']` after we import the zpool since that translates to a database insert which increments the column `id` by design
2. because this failed, it show-cased the fact that `another_pool()` helper statically defined the name of the zpool so it caused a myriad of other tests to fail. I've, instead, generated a random zpool name each time `another_pool()` is called to prevent this cascading effect of failures from taking place.

2023-02-08 19:44 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120261

2023-02-08 21:39 UTC, themylogin commented
> I've, instead, generated a random zpool name each time another_pool() is called to prevent this cascading effect of failures from taking place.

Unfortunately it won't help. If we are unable to destroy the `test` pool then we won't be able to create a new `another_pool` because we have a limited amount of disks and they all will be busy, so pool name won't really matter here. Tests, on the other hand, get more complicated with the dynamic pool name.

2023-02-08 21:42 UTC, themylogin requested changes

2023-02-08 21:42 UTC, themylogin commented on src/middlewared/middlewared/test/integration/assets/pool.py
> +def another_pool(name=None, data=None, topology=None):
It'll have more sense to omit this parameter and just to `data.setdefault("name", generate_random_zpool_name())` as `data` is indeed the dictionary used for `pool.create`. But I also don't think random name will be useful at all, please see my comment above.

2023-02-09 00:03 UTC, yocalebo commented
> > I've, instead, generated a random zpool name each time another_pool() is called to prevent this cascading effect of failures from taking place.
> 
> Unfortunately it won't help. If we are unable to destroy the `test` pool then we won't be able to create a new `another_pool` because we have a limited amount of disks and they all will be busy, so pool name won't really matter here. Tests, on the other hand, get more complicated with the dynamic pool name.

Sure, the non-HA VM has like 10 or 11 unused disks so this wouldn't be a problem. Our HA VMs, however, are a different story. I've reverted to just fixing the original problem for now.

2023-02-09 11:13 UTC, themylogin approved these changes

2023-02-09 11:13 UTC, merged