ZFS tunables
truenas/middleware pull request #10783
Opened 2023-03-01 18:47 UTC by themylogin

2023-03-01 18:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-119809

2023-03-01 18:48 UTC, themylogin commented
time 8:00

2023-03-05 18:28 UTC, themylogin commented
@yocalebo need your feedback on this before moving on with autotune

2023-03-08 18:36 UTC, yocalebo requested changes

2023-03-08 18:36 UTC, yocalebo commented on src/middlewared/middlewared/plugins/tunables.py
> +                await self.middleware.call('tunable.set_zfs_parameter', data['var'], data['value'])
We should set parameter and then update initramfs.

2023-03-09 18:18 UTC, yocalebo approved these changes

2023-03-09 20:47 UTC, merged