Add some casefolded filters
truenas/middleware pull request #10808
Opened 2023-03-07 14:44 UTC by anodos325

Add special behavior where capital C prefix
in filterop performs a casefolded version of
the filter. This is useful in cases where
we're dealing with external protocols that are
case-insensitive.

2023-03-07 16:00 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-120647

2023-03-07 17:13 UTC, anodos325 commented
Throwing WIP back on because of some CI failures.

2023-03-07 20:40 UTC, anodos325 commented
Last custom jenkins run came up clean.

2023-03-08 09:54 UTC, themylogin requested changes
Also `casefold` seems confusing here, like there is some reason to perform indeed `casefold` and not, for example, just `lower`

2023-03-08 09:54 UTC, themylogin commented on src/middlewared/middlewared/utils/__init__.py
> +    case_opmap = {
Can we just use operators from `opmap` but run `casefold` against arguments first? That way we won't have duplicate code.

2023-03-08 16:11 UTC, themylogin approved these changes

2023-03-08 16:25 UTC, merged