Expand validation of user home directories
truenas/middleware pull request #10994
Opened 2023-03-28 16:44 UTC by anodos325

We should catch following cases and turn them into informative validation errors:

* New home directory doesn't exist and parent directory is on RO dataset
* New home directory doesn't exist and parent directory is immutable
* New home directory exists and is on RO dataset or immutable

Since we're already having to get mount information, this commit adds an additional check for filesystem type in the returned mount info. If any validation errors have been added, then skip more expensive checks using libzfs.

2023-03-28 16:44 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121206

2023-03-28 17:29 UTC, themylogin requested changes
We can easily add integration tests here

2023-05-02 18:24 UTC, william-gr commented
This has been lingering for some time.
Wonder if we should merge and create another ticket for the follow up.

2023-05-02 19:05 UTC, anodos325 commented
I can add tests soon-ish. We were going through variations of having various jenkins things broken when I was preparing to write tests.

2023-05-18 12:50 UTC, yocalebo approved these changes

2023-05-18 18:36 UTC, merged