Update forward_lookup to support A/AAAA records by default
truenas/middleware pull request #11092
Opened 2023-04-11 17:37 UTC by mgrimesix

Input parameters:
* record_type changed to a list of record_types. Default is ['A', 'AAAA']. 'SRV' and 'CNAME' remain singular and cannot be requested in combination with the others. NOTE: With the default record_types selection, hosts that support both IPv4 and IPv6 will return entries for both 'A' and 'AAAA' records.
* Added 'throw_exception_on'. Default to 'host_failure'.  Options are 'never', 'any_failure', 'host_failure', all_failure'. Output parameters and exception reporting behavior (with default selection) remain unchanged.

2023-04-11 17:37 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121309

2023-04-11 20:14 UTC, anodos325 commented on src/middlewared/middlewared/plugins/dns_client.py
> +        Str('throw_exception_on', default='host_failure', enum=['never', 'any_failure', 'host_failure', 'all_failure']),
We typically make enums all caps, e.g. NEVER. I believe our convention is `raise_error` for cases where caller can control exception handling.

2023-04-11 20:41 UTC, themylogin requested changes

2023-04-12 14:39 UTC, themylogin approved these changes

2023-04-12 14:42 UTC, anodos325 approved these changes

2023-04-12 14:47 UTC, merged