Remove lvm on disks used for pool creation
truenas/middleware pull request #11111
Opened 2023-04-13 19:09 UTC by Qubad786

## Problem

If a disk device has LVM configured - wipe fails for that disk as the disk is in use.
The same logic we use for removing md mirrors on disks should be used for LVM as well to remove LVM on disks in question which are going to be wiped for pool creation.

## Solution

We generate a mapping of each disk and it's associated logical volumes and disk groups. A disk can have multiple partitions and each partition can have separate logical volumes configured - this has been taken care of as well with the mapping we generate.
Once the mapping is in place we remove logical volumes on those disks and pool creation succeeds.

2023-04-13 19:09 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121347

2023-04-13 22:23 UTC, themylogin requested changes
How do LVMs appear there in the first place?

Can we somehow simulate that situation to have an integration test?

2023-04-13 22:23 UTC, themylogin commented on src/middlewared/middlewared/pytest/unit/plugins/disk/test_normalized_disk_name.py
> +@contextlib.contextmanager
`contextlib.nullcontext()`

2023-04-13 22:23 UTC, themylogin commented on src/middlewared/middlewared/pytest/unit/plugins/disk/test_normalized_disk_name.py
> +        with patch('middlewared.plugins.disk_.disk_info.DiskService.is_partition') as is_partition_fuc:
`with patch('middlewared.plugins.disk_.disk_info.DiskService.is_partition', Mock(return_value=is_partition))`

2023-04-14 02:08 UTC, igpit commented
> How do LVMs appear there in the first place?

E.g. when the admin plugs in a disk with pre-existing data which he then wants to use in TN ;)

2023-04-14 08:58 UTC, yocalebo requested changes

2023-04-14 08:58 UTC, yocalebo commented on src/middlewared/middlewared/plugins/disk_/lvm.py
> +                await run(
I don't like forking+execing in the main event loop. Especially in a for loop.

2023-06-28 16:42 UTC, william-gr commented
Closing this PR for now, please see ticket.

2023-06-28 16:42 UTC, closed without merging