Replication manager role
truenas/middleware pull request #11136
Opened 2023-04-20 09:12 UTC by themylogin

2023-04-20 09:13 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121581

2023-05-24 10:17 UTC, themylogin commented
No authentication/privilege-related test failures were found https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/814/#showFailuresLink

2023-05-24 14:35 UTC, yocalebo requested changes
We need a comment describing what this does since it's a significant feature. We then need to copy whatever is written here and put it in an internal document (or NEP).

We also actually need documentation on how other developers can add these roles to other endpoints to get the desired effect. (again, putting it all in a document)

2023-05-24 14:35 UTC, yocalebo commented on src/middlewared/middlewared/role.py
> +    def roles_for_fole(self, role):
`fole` has negative connotation depending on the person's native tongue. I'm  not sure if it has another meaning but nonetheless, it's not a valid method name.

2023-05-30 15:10 UTC, yocalebo commented
> @yocalebo I added a middleware developer doc

Developer documentation is good but please also add a summary of what this does to the actual GitHub PR. This is also a new ticket and not associated to the ticket that I created which lists vastly more detail on why we are doing this and the general idea.

2023-07-07 12:29 UTC, sonicaj approved these changes

2023-07-10 11:36 UTC, yocalebo requested changes

2023-07-10 11:36 UTC, yocalebo commented on src/middlewared/middlewared/plugins/account_/privilege.py
> +                compose['roles'] |= self.middleware.role_manager.roles_for_fole(role)
`roles_for_fole` is back
```suggestion
                compose['roles'] |= self.middleware.role_manager.roles_for_fole(role)
```

2023-07-14 10:30 UTC, anodos325 approved these changes

2023-07-14 10:37 UTC, merged

2023-08-11 09:52 UTC, themylogin commented
time 30:00