NAS-121688 / 23.10 / test_account_ssh_key.py
truenas/middleware pull request #11167
Opened 2023-04-27 08:47 UTC by themylogin

2023-04-27 16:40 UTC, themylogin commented
time 3:00

2023-04-28 13:52 UTC, yocalebo approved these changes
Looks good, but let's wait on @anodos325 final review before merge, please.

2023-04-28 14:09 UTC, anodos325 commented
No commit message explaining change.

2023-05-01 07:58 UTC, themylogin commented
@anodos325 @yocalebo the ticket opener expects exactly the opposite, what should we do here?

2023-05-15 11:33 UTC, anodos325 approved these changes

2023-05-15 11:38 UTC, anodos325 commented
I'd go ahead with deletion. I'll look at ticket, but I don't think the ticket opener's request makes sense.

2023-05-21 12:16 UTC, yocalebo requested changes

2023-05-21 12:16 UTC, yocalebo commented on src/middlewared/middlewared/plugins/account.py
> +                    shutil.rmtree(os.path.join(user['home'], '.ssh'))
Blocking IO

2023-05-21 12:16 UTC, yocalebo commented on src/middlewared/middlewared/plugins/account.py
> +            Bool('delete_ssh', default=True),
This doesn't need to be an option. When a user is deleted, we should always remove the .ssh dir.

2023-05-21 12:54 UTC, yocalebo approved these changes

2023-05-21 13:11 UTC, themylogin commented
time 1:00

2023-05-21 13:11 UTC, merged