NAS-121871 / 23.10 / Make sure unencrypted dataset cannot be created inside an encrypted dataset
truenas/middleware pull request #11256
Opened 2023-05-08 16:36 UTC by sonicaj

2023-05-08 16:36 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121871

2023-05-08 16:37 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-121871

2023-05-08 17:08 UTC, themylogin requested changes
Tests

2023-05-08 21:24 UTC, yocalebo requested changes

2023-05-08 21:24 UTC, yocalebo commented on src/middlewared/middlewared/plugins/pool_/dataset.py
> +        if parent_ds['encrypted'] and data['encryption'] is False and not inherit_encryption_properties:
We probably have to check the entire ancestor tree. (i.e. encrypted->parentA->childA)

2023-05-09 13:19 UTC, themylogin reviewed
What are the issues?

We currently allow putting system dataset on a pool with an encrypted root dataset (system dataset will be unencrypted), will there be any problems with that?

2023-05-09 13:37 UTC, sonicaj commented
@themylogin when native zfs encryption support was added, motivation was to keep the design simple and not introduce undue complexity.
Wrt system dataset, no it is fine - in terms of immediate problem which occurs with this is child getting mounted where parent is locked i.e
`/mnt/pool/encrypted/child`, we will see people writing to `encrypted` even it is locked whereas child is mounted.

2023-05-09 13:44 UTC, themylogin approved these changes

2023-05-09 14:00 UTC, yocalebo approved these changes

2023-05-09 14:20 UTC, merged