Fix `KeyError: devname`
truenas/middleware pull request #11612
Opened 2023-06-30 19:09 UTC by themylogin

2023-06-30 19:09 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-122618

2023-06-30 19:13 UTC, yocalebo requested changes
I specifically avoid disk.query here for performance reasons.

2023-06-30 19:53 UTC, yocalebo approved these changes

2023-07-01 18:17 UTC, merged

2023-08-11 09:40 UTC, themylogin commented
time 0:30