Collect disk temperature stats at 30 min intervals
truenas/middleware pull request #11964
Opened 2023-08-28 19:16 UTC by Qubad786

## Problem

Currently, smartd collects data at a 30-minute interval. However, our current data collection process from smartd involves allocating disk space for a 1-second interval. This mismatch between the collection intervals and disk space allocation intervals is causing excessive disk space allocation and unnecessarily cpu is being consumed as well.

## Solution

To address this, we need to adjust our data collection process to match the 30-minute interval used by smartd for data collection.

2023-08-28 19:18 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123755

2023-08-28 19:30 UTC, yocalebo commented on src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
> +        self.update_every = 30 * 60
Let's add a comment here explaining why we're doing this please 👍 (i.e. "smartd daemon only queries drive temps every 30mins so the files won't be updated but once every 30ish minutes") or something alone those lines 😄

2023-08-29 09:55 UTC, themylogin requested changes

2023-08-30 11:30 UTC, yocalebo commented on src/freenas/usr/lib/netdata/python.d/smart_log.chart.py
> +        self.update_every = 30 * 60
@themylogin no it's not.

2023-08-30 11:31 UTC, merged