Remove system dataset syslog
truenas/middleware pull request #12034
Opened 2023-09-02 09:09 UTC by themylogin

2023-09-02 09:09 UTC, themylogin commented
time 0:30

2023-09-02 09:09 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123773

2023-09-05 11:34 UTC, yocalebo requested changes
I just merged in a migration for a PR that I opened last week so this one will need to be updated.

2023-09-05 11:54 UTC, yocalebo commented
retest this please

2023-09-05 12:27 UTC, yocalebo approved these changes

2023-09-05 12:36 UTC, merged