Roles
truenas/middleware pull request #12073
Opened 2023-09-11 10:09 UTC by themylogin

2023-09-11 10:09 UTC, themylogin commented
time 4:00

2023-09-11 10:10 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123910

2023-09-26 10:50 UTC, themylogin commented
@bmeagherix @anodos325 ping

2023-09-26 11:28 UTC, anodos325 commented
Does this mean that a readonly user will have read access to the user DB table?

2023-09-26 14:57 UTC, anodos325 requested changes
We should have some handling for private fields in READONLY role otherwise there is potential for privilege escalation / unintended disclosure of information.

2023-09-26 21:26 UTC, bmeagherix requested changes
What is there looks very good, but I agree with Andrew's comment:
> We should have some handling for private fields in READONLY role otherwise there is potential for privilege escalation / unintended disclosure of information.

(For example, once we add a READ role covering it, I could envisage wanting to redact CHAP credentials from `iscsi.auth.query`.)

Have we worked out yet how the webui will behave for a user with READONLY role?

Wrt tests, IMO it would be good to add success/failure method calls in nfs, smb & iscsi for SHARING_READ role.  Also success calls (using the same methods) for SHARING_WRITE role.

2023-09-28 11:24 UTC, yocalebo commented
After some discussion, hiding `private=True` fields from `query` endpoints is a huge non-trivial change that needs to happen in another PR. This PR just adds the exact items that were requested from management so we're going to hold off on hiding sensitive fields from query endpoints. I will open a separate ticket and link it to this one to implement said feature. For now, let's forgo that thought process and get another round of reviews please @anodos325 @bmeagherix

2023-09-28 13:34 UTC, bmeagherix requested changes
Suggest adding tests for success/failure method calls in nfs, smb & iscsi for SHARING_READ role.

Also success calls (using the same methods) for SHARING_WRITE role.

2023-10-30 13:57 UTC, anodos325 commented
I think we should add privilege table entries for each of the roles that don't already exist (we already have an admin one with full control).

2023-10-30 13:59 UTC, anodos325 commented
I think we should also expand the dump of logged-in user `auth.me` to include information about privileges assigned to user (based on group membership).

2023-10-30 15:46 UTC, themylogin commented
> I think we should add privilege table entries for each of the roles that don't already exist (we already have an admin one with full control).

@yocalebo what do you think of this? Looks questionable, we'll have a ton of useless entries by default.

2023-10-30 16:54 UTC, anodos325 commented
> > I think we should add privilege table entries for each of the roles that don't already exist (we already have an admin one with full control).
> 
> @yocalebo what do you think of this? Looks questionable, we'll have a ton of useless entries by default.

Well, maybe not all of them, but one or two that cover some basic common use-cases (like the READONLY access). In that way it can kind of act as template for users to think "oh this is how it's done". Just a thought.

2023-10-30 17:20 UTC, themylogin commented
I agree on adding "readonly user" built-in privilege. @yocalebo ?

2023-10-30 20:42 UTC, yocalebo commented
@themylogin yeah adding read only is a good first step for now

2023-10-30 21:17 UTC, anodos325 commented on src/middlewared/middlewared/alembic/versions/24.04/2023-10-30_21-02_readonly_privilege.py
> +        "VALUES ('READONLY', 'Readonly Users', '[]', '[]', '[]', 0, '[\"READONLY\"]')"
I believe per our previous conversations about sensitive info being exposed to READONLY users that we may want to explicitly name something like "READONLY ADMINISTRATORS", correct?

2023-10-31 14:39 UTC, yocalebo approved these changes
Great job but please wait for @anodos325 and @bmeagherix approval before merge.

2023-10-31 15:24 UTC, anodos325 approved these changes

2023-10-31 15:26 UTC, merged

2023-10-31 15:26 UTC, themylogin commented
time 8:00