Enable exporting reporting data to graphite
truenas/middleware pull request #12077
Opened 2023-09-11 16:29 UTC by Qubad786

## Context

It was requested that we add ability to export reporting data to graphite similar to what we used to do before and while we are doing this also make sure the approach is implementation agnostic so we can add more relevant export types as well.

Here changes have been made to the reporting system to ensure that the configuration aligns with the use of Netdata for reporting. Specifically, the reporting system is updated to support Netdata's metrics export to Graphite, as Collectd is no longer used. This involves creating a new endpoint within the reporting system, such as `reporting.exporters`, which exposes methods for creating, deleting, and updating Netdata export configurations.

The following parameters should be specified to enable Graphite as the reporting destination for Netdata:

1. **enable**: This parameter enables a specific instance of the export.
2. **name**: It specifies a unique instance name for Netdata. If multiple instances are configured, each must have a distinct name.
3. **attributes.destination_ip**: This parameter sets the IP address of the Graphite server.
4. **attributes.destination_port**: It specifies the port on which the Graphite server is listening.
5. **attributes.prefix**: This parameter defines a prefix that will be prepended to all Netdata metrics sent to Graphite.
6. **attributes.hostname**: It is used to specify the hostname to append to the metrics after the prefix.
7. **attributes.update_every**: This parameter determines the interval at which metrics are updated.
8. **attributes.buffer_on_failures**: It specifies the tolerance for update failures.
9. **attributes.send_names_instead_of_ids**: This option controls whether to send chart names instead of IDs.
10. **attributes.matching_charts**: This parameter allows specifying a regular expression for Netdata charts that should be sent to the Graphite server.
11. **type**: Currently, only `GRAPHITE` is supported. This parameter simplifies the integration of other exporters available in Netdata.

By implementing these changes and ensuring that the reporting system is aligned with Netdata's Graphite export configuration, the reporting process will be accurate and efficient and the approach is generic too so we can add more exporters in the future with ease.

## References

- [Netdata Documentation](https://learn.netdata.cloud/docs/agent/collectors/plugins.d.plugin/graphite.plugin)
- [Netdata Exporting Ref](https://learn.netdata.cloud/docs/exporting/exporting-reference)

2023-09-11 16:29 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123668

2023-09-13 13:00 UTC, yocalebo approved these changes
This looks good to me, however, please wait for Vlad's review since it's touching database.

2023-09-14 12:39 UTC, themylogin requested changes

2023-09-14 12:39 UTC, themylogin commented on src/middlewared/middlewared/alembic/versions/24.04/2023-09-07_19-50_add_exporting_table_for_reporting.py
> +            f"(true, 'GRAPHITE', 'netdata', '{json.dumps(attributes)}')"
If `graphite_ip[0]` for some reason contains `'`, it will be an SQL error. Please use bind parameters instead

2023-09-18 11:18 UTC, yocalebo commented
@themylogin ping

2023-09-19 18:07 UTC, themylogin approved these changes

2023-09-19 19:13 UTC, merged

2023-11-10 18:04 UTC, Qubad786 commented
backport