Mark minio service as deprecated
truenas/middleware pull request #12101
Opened 2023-09-14 14:42 UTC by themylogin

2023-09-14 14:43 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124062

2023-09-14 14:43 UTC, themylogin commented
time 1:00

2023-09-14 17:59 UTC, yocalebo commented
Waiting on docs team to see if we have a URL for core.

2023-09-18 16:27 UTC, yocalebo requested changes

2023-09-18 16:27 UTC, yocalebo commented on src/middlewared/middlewared/plugins/update_/install_freebsd.py
> +                    "Additional details are available from https://www.truenas.com/docs/scale/scaledeprecatedfeatures/."
I spoke to the docs team and this is the URL we need to use for CORE
```suggestion
                    "Additional details are available from https://www.truenas.com/docs/core/13.0/gettingstarted/deprecations."
```

2023-09-18 17:03 UTC, yocalebo approved these changes

2023-09-18 17:03 UTC, merged