Expose SMB auditing feature
truenas/middleware pull request #12129
Opened 2023-09-19 17:22 UTC by anodos325

This PR expands the SMB share schema to add SMB auditing configuration parameters:

`enable` - enable auditing for the SMB share
`watch_list` - optional parameter to restrict auditing to
    a list of groups. SMB ops will be audited if user token
    contains one of listed groups.
`ignore_list` - optional parameter to skip auditing for a
    a list of groups. SMB ops will _not_ be audited if user
    token contains one of listed groups.

NOTE: if user token contains group in watch_list and in ignore_list, then watch_list takes precedence.

2023-09-19 17:23 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123955

2023-09-19 17:24 UTC, anodos325 commented
Depends on this PR https://github.com/truenas/middleware/pull/11820

2023-09-20 11:29 UTC, yocalebo requested changes
Will need to have updated db migration.

2023-09-22 00:50 UTC, yocalebo approved these changes

2023-09-22 02:19 UTC, merged