Fix cases where Str is used instead of Password
truenas/middleware pull request #12364
Opened 2023-10-19 20:11 UTC by anodos325

The Password class ensures that the string being handled is treated as private and redacted from relevant logs. This commit fixes many cases where the incorrect class was used for hanlding passwords. In some of the instances, the Str had the private parameter set and so there is no functional change, but it's beneficial to clearly mark places where passwords are being handled as such in the codebase.

For the purpose of this PR, API keys and tokens are also treated as password-equivalent strings.

2023-10-19 20:12 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124719

2023-10-19 22:07 UTC, bmeagherix requested changes
All looks good so far.

Would suggest adding `secret` and `peersecret` from [src/middlewared/middlewared/plugins/iscsi_/auth.py](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/iscsi_/auth.py)

I also **wonder** about:

-  `secret` in [add_jwt_secret](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/gluster_linux/local_events.py) and [GlusterEventsdService.create](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/gluster_linux/eventsd.py) (and `bearer_token`)
- a few `client_secret` wrt rclone/remote/*.py
- [application_secret](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/acme_protocol_/authenticators/ovh.py) and [secret_access_key](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/acme_protocol_/authenticators/route53.py)

2023-10-20 00:21 UTC, bmeagherix approved these changes
LGTM.  Nice!

2023-10-20 14:46 UTC, sonicaj approved these changes

2023-10-20 15:11 UTC, merged