Add roles for SMB share ACL and status
truenas/middleware pull request #12450
Opened 2023-11-03 19:46 UTC by anodos325

This allows properly authorized users to view / set SMB share ACL and view SMB status.

2023-11-03 19:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125055

2023-11-08 16:19 UTC, bmeagherix requested changes
Add test for `client_count`?

Also, do the `get_remote_acl` and `presets` APIs need to have a role set?

2023-11-13 15:11 UTC, bmeagherix approved these changes

2023-11-13 15:27 UTC, mgrimesix approved these changes

2023-11-14 14:18 UTC, merged