Do not allow changing an alias if it is being consumed by apps
truenas/middleware pull request #12471
Opened 2023-11-09 13:48 UTC by sonicaj

This commit adds changes to not allow changing an alias if it's being consumed by apps.

2023-11-09 13:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124761

2023-11-09 18:32 UTC, yocalebo requested changes

2023-11-09 18:32 UTC, yocalebo commented on src/middlewared/middlewared/plugins/network.py
> +                f'{node_ip!r} is being consumed by Applications and before changing it, please use a different node IP'
```suggestion
                f'{node_ip!r} is being consumed by Applications, please use a different node IP'
```

2023-11-09 18:36 UTC, yocalebo approved these changes

2023-11-09 18:40 UTC, yocalebo requested changes
Hmm, actually looks like unit tests need to be updated.

2023-11-09 18:42 UTC, sonicaj commented
@yocalebo, yup - fixed

2023-11-09 18:43 UTC, yocalebo approved these changes

2023-11-10 11:53 UTC, merged

2023-11-10 11:53 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-124761 is targeted to the following versions which have not received their corresponding PRs: 23.10.1

2023-11-10 11:54 UTC, sonicaj commented
backport