Add cobia reporting exporter migration to dragonfish
truenas/middleware pull request #12485
Opened 2023-11-13 13:43 UTC by Qubad786

## Context

With reporting exporter changes backported to cobia - a merge migration has been added to master and the migration also added to dragonfish.

2023-11-13 13:43 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125204

2023-11-13 13:43 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125204

2023-11-13 16:41 UTC, yocalebo requested changes
Check the build log but this fails during alembic migration phase. Stating it can't find `system_reporting` table.

2023-11-13 17:00 UTC, themylogin requested changes

2023-11-13 17:00 UTC, themylogin commented on src/middlewared/middlewared/alembic/versions/23.10/2023-11-10_23-19_add_exporting_table_for_reporting.py
> +    if 'reporting_exporters' in inspector.get_table_names():
Good job encountering this! Please also add this to the appropriate docs section for a specific example on how to make an idempotent migration

2023-11-14 14:25 UTC, themylogin commented on docs/source/database/migrations.rst
> +* An example for such a case is `src/middlewared/middlewared/alembic/versions/23.10/2023-11-10_23-19_add_exporting_table_for_reporting.py`
Be more specific please. “For example, one can check if a table already exists by doing xxx, you can see file yyy as an example’.

2023-11-16 17:56 UTC, themylogin approved these changes

2023-11-16 17:59 UTC, yocalebo approved these changes

2023-11-16 18:00 UTC, merged