hide private=True fields from query endpoints for non-admins
truenas/middleware pull request #12705
Opened 2023-12-12 14:45 UTC by themylogin

The PR is made against [fix-rest-audit](https://github.com/truenas/middleware/pull/12644) because it requires the work done in that PR

2023-12-12 14:45 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124387

2023-12-12 14:56 UTC, yocalebo commented on src/middlewared/middlewared/plugins/mail.py
> +        Password('pass', null=True, private=True, required=True),
`Password` class already has `private=True` ?

2023-12-15 12:40 UTC, yocalebo requested changes
Looks like conflicts need to be resolved.

2023-12-19 11:50 UTC, themylogin commented
time 40:00

2023-12-19 11:51 UTC, themylogin commented
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1507/

2023-12-19 18:17 UTC, yocalebo commented
> https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1507/

133 failed tests so hard to approve this for now.

2023-12-19 18:20 UTC, yocalebo commented
Closer inspection seems like the failures are related to this PR: https://github.com/truenas/middleware/pull/12673

2023-12-22 11:21 UTC, themylogin commented
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1521/

2023-12-23 14:38 UTC, yocalebo approved these changes

2023-12-24 10:41 UTC, merged

2023-12-24 10:41 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.