Update graphite exporter defaults
truenas/middleware pull request #12734
Opened 2023-12-15 17:38 UTC by Qubad786

## Problem

Default values of graphite exporter were pointing to a fixed scale release which does not sit well and needs to be updated on scale release changes.

## Solution

Update defaults to not point to a specific scale release to avoid changing/managing them each time.

2023-12-15 17:44 UTC, themylogin commented on src/middlewared/middlewared/alembic/versions/23.10/2023-11-10_23-19_add_exporting_table_for_reporting.py
> +    hostname = get_hostname()
We should use the hostname specified in the networking configuration, not this

2023-12-15 17:45 UTC, themylogin requested changes
Same for second migration

2023-12-19 18:15 UTC, yocalebo commented
@themylogin ping

2023-12-20 16:10 UTC, themylogin approved these changes
Thank you!

2023-12-20 16:11 UTC, merged

2023-12-20 16:11 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.