Handle missing users and groups in NFS share configuration
truenas/middleware pull request #12800
Opened 2023-12-26 23:17 UTC by mgrimesix

### Problem
On upgrade, if `maproot` or `mapall` is configured on an NFS share and the user or group is deleted as part of the upgrade, then all NFS shares end up disabled.

### Fix
- In nfs exports mako add check for required users or groups and disable NFS shares that use missing users or groups.
- Add oneshot alert when missing user or group is detected.   Remove oneshot alert when share configuration is repaired.
- Enhance reporting on attempt to configure NFS share with invalid user or group setting

### Other fixes/improvements
- Add name-to-id and id-to-name helper routines for both user and group
- Add CI test for missing user and group with NFS `maproot` and `mapall` configuration options
- Some refactoring of the NFS CI test module

2023-12-26 23:17 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125621

2023-12-27 12:55 UTC, yocalebo requested changes

2023-12-27 12:55 UTC, yocalebo commented on src/middlewared/middlewared/etc_files/exports.mako
> +            raise KeyError
We should set `__context__` here so this needs to look like
```
raise KeyError(f'Missing {key}') from None
```

2023-12-27 12:55 UTC, yocalebo commented on src/middlewared/middlewared/etc_files/exports.mako
> +                    raise KeyError
Same review that I gave earlier.

2023-12-27 12:56 UTC, anodos325 commented on src/middlewared/middlewared/plugins/account_/internal_cache.py
> +    async def username_to_uid(self, user_name):
This basically duplicates `user.get_user_obj` We should just use the public method. It raises KeyError if user doesn't exist.

2023-12-28 21:14 UTC, anodos325 commented on tests/api2/test_300_nfs.py
> +def test_15_id_to_name(data):
Duplicate test number.

2023-12-28 21:15 UTC, anodos325 commented on tests/api2/test_300_nfs.py
> +def test_15_id_to_name(data):
Can we remove these tests since methods were removed?

2023-12-28 21:19 UTC, anodos325 approved these changes

2023-12-28 21:20 UTC, yocalebo approved these changes
Thanks!

2023-12-28 21:44 UTC, merged

2023-12-28 21:45 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.