Add VM and VM device roles
truenas/middleware pull request #12857
Opened 2024-01-07 11:11 UTC by Qubad786

## Context

PR adds roles for VM and VM device services endpoints.
Adds `READONLY` role for public endpoints in use by WebUI.

2024-01-07 11:11 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125784

2024-01-08 16:57 UTC, themylogin requested changes
VM display device has password, which is marked as private. This means that, in general case, it should be redacted when displaying to a read-only user. Please confirm if this is the case with @yocalebo and, if necessary, add the necessary logic and the test to `test_account_privilege_role_private_fields.py`.

2024-01-11 15:05 UTC, yocalebo commented
@Qubad786 friendly ping 👍

2024-01-15 14:22 UTC, themylogin approved these changes
Thank you!

2024-01-15 14:23 UTC, merged

2024-01-15 14:23 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.