Add new builtin groups for builtin roles
truenas/middleware pull request #12897
Opened 2024-01-15 21:07 UTC by themylogin

2024-01-15 21:08 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-125045

2024-01-15 21:24 UTC, themylogin commented
https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/API%20Tests%20-%20TrueNAS%20SCALE%20with%20middleware%20reinstalled%20from%20a%20branch%20Incremental/1618/

2024-01-15 21:30 UTC, themylogin commented
time 4:00

2024-01-16 12:35 UTC, yocalebo requested changes

2024-01-16 12:35 UTC, yocalebo commented on src/middlewared/middlewared/alembic/versions/24.04/2024-01-15_20-10_builtin_roles_groups.py
> +        "UPDATE account_privilege SET builtin_name = 'READONLY_ADMININSTATOR', name = 'Read-Only Administator', "
```suggestion
        "UPDATE account_privilege SET builtin_name = 'READONLY_ADMININSTRATOR', name = 'Read-Only Administator', "
```

2024-01-16 12:35 UTC, yocalebo commented on src/middlewared/middlewared/alembic/versions/24.04/2024-01-15_20-10_builtin_roles_groups.py
> +        "UPDATE account_privilege SET builtin_name = 'SHARING_ADMINISTRATOR', name = 'Sharing Administator', "
```suggestion
        "UPDATE account_privilege SET builtin_name = 'SHARING_ADMINISTRATOR', name = 'Sharing Administrator', "
```

2024-01-16 12:35 UTC, yocalebo commented on src/middlewared/middlewared/plugins/account_/privilege.py
> +    READONLY_ADMININSTATOR = "READONLY_ADMININSTATOR"
```suggestion
    READONLY_ADMINISTRATOR = "READONLY_ADMINISTRATOR"
```

2024-01-16 12:35 UTC, yocalebo commented on src/middlewared/middlewared/plugins/account_/privilege.py
> +            elif builtin_privilege == BuiltinPrivileges.READONLY_ADMININSTATOR:
```suggestion
            elif builtin_privilege == BuiltinPrivileges.READONLY_ADMINISTRATOR:
```

2024-01-16 14:25 UTC, yocalebo commented
There will be conflicts after this PR is merged so holding on on approving right now: https://github.com/truenas/middleware/pull/12893

2024-01-16 14:31 UTC, anodos325 approved these changes

2024-01-16 15:40 UTC, yocalebo approved these changes

2024-01-16 15:47 UTC, merged

2024-01-16 15:55 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.