Fix pagination parameters
truenas/middleware pull request #12970
Opened 2024-01-24 15:27 UTC by Qubad786

## Problem

`offset` and `limit` parameters were being applied twice, one at the sql level and the then again at middleware level.

## Fix

PR fixes the problem by making sure this is not done at database level keeping in line with some other parameters we remove as well already.

2024-01-24 15:28 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-126080

2024-01-24 15:33 UTC, yocalebo commented on src/middlewared/middlewared/service/crud_service.py
> +            for option in ['count', 'get', 'limit', 'offset', 'select']:
Should we make a global object like
```
PAGINATION_OPTS = ('count', 'get', 'limit', 'offset', 'select')
```

And use it in this loop instead? Ideally the global variable might help us catch this in the future? Furthermore, we should probably add some tests for these.

2024-01-24 15:38 UTC, themylogin requested changes
Agreed on the tests part

2024-01-29 13:42 UTC, yocalebo commented
@themylogin ping

2024-01-31 16:10 UTC, themylogin approved these changes

2024-01-31 16:11 UTC, yocalebo approved these changes

2024-01-31 17:32 UTC, merged

2024-01-31 17:33 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.