Do not use interface rename logic on systems that have NICs with dupl…
truenas/middleware pull request #13003
Opened 2024-01-26 13:50 UTC by themylogin

…icate hardware link addresses

2024-01-26 13:50 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127008

2024-01-26 13:51 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127008

2024-01-26 14:29 UTC, yocalebo requested changes

2024-01-26 14:29 UTC, yocalebo commented on src/middlewared/middlewared/plugins/interface/link_address.py
> +                raise ValueError(f"Interfaces {self.by_link_address[link_address]['name']!r} and {i['name']!r} have "
Let's raise a custom exception class and catch it specifically and log a message that caters to this scenario.

2024-01-29 15:32 UTC, merged

2024-01-29 15:32 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-01-29 17:32 UTC, themylogin commented
backport