NAS-124714 / 24.10 / Remove `crypto` module usage
truenas/middleware pull request #13083
Opened 2024-02-05 12:37 UTC by themylogin

The `crypt` module is slated to be removed in python3.13.

2024-02-05 12:38 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-124714

2024-02-05 12:38 UTC, themylogin commented
time 1:00

2024-02-05 15:52 UTC, anodos325 approved these changes

2024-02-05 20:49 UTC, bmeagherix requested changes
FWI, looks like the `crypt` module is also being used in [plugins/auth_/authenticate.py](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/auth_/authenticate.py#L69)

2024-02-05 21:20 UTC, themylogin commented
> FWI, looks like the `crypt` module is also being used in [plugins/auth_/authenticate.py](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/auth_/authenticate.py#L69)

@bmeagherix I don't understand, what changes are you suggesting?

2024-02-05 21:22 UTC, themylogin commented
@yocalebo 
```
root@b50f62b2f4af:/# rm /usr/local/lib/python3.12/crypt.py 
root@b50f62b2f4af:/# python3.12
Python 3.12.1 (main, Feb  1 2024, 04:22:19) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import crypt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'crypt'
>>> from passlib.hash import sha512_crypt
>>> sha512_crypt.hash('test')
'$6$rounds=656000$Wgo04NdlW5Ut06a.$biRRaEnSxQWPC3L1KtNPKmwBn7h9LROP1cfFtSuEryXHfCjUXuXWsEi3PP7/I4usm.QnsIJaQOThFGmBZ2DwZ0'
>>> sha512_crypt.verify('test', '$6$rounds=656000$Wgo04NdlW5Ut06a.$biRRaEnSxQWPC3L1KtNPKmwBn7h9LROP1cfFtSuEryXHfCjUXuXWsEi3PP7/I4usm.QnsIJaQOThFGmBZ2DwZ0')
True
```

2024-02-05 21:22 UTC, themylogin commented on src/middlewared/middlewared/plugins/account.py
> +    return sha512_crypt.hash(cleartext)
@yocalebo `hashlib` does not support this.

`crypt` module is deprecated and being removed.

2024-02-06 02:04 UTC, bmeagherix commented
> > FWI, looks like the `crypt` module is also being used in [plugins/auth_/authenticate.py](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/auth_/authenticate.py#L69)
> 
> @bmeagherix I don't understand, what changes are you suggesting?

@themylogin Your PR seems to be wrt removing the use of the python `crypt` module.

I was just pointing out that it is also currently used elsewhere in middleware, so you PR isn't complete.

2024-02-06 10:55 UTC, themylogin commented
@bmeagherix my PR removes `crypt` module usage from [plugins/auth_/authenticate.py](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/auth_/authenticate.py#L69)

2024-02-06 11:31 UTC, anodos325 commented
> @yocalebo
> 
> ```
> root@b50f62b2f4af:/# rm /usr/local/lib/python3.12/crypt.py 
> root@b50f62b2f4af:/# python3.12
> Python 3.12.1 (main, Feb  1 2024, 04:22:19) [GCC 12.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import crypt
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ModuleNotFoundError: No module named 'crypt'
> >>> from passlib.hash import sha512_crypt
> >>> sha512_crypt.hash('test')
> '$6$rounds=656000$Wgo04NdlW5Ut06a.$biRRaEnSxQWPC3L1KtNPKmwBn7h9LROP1cfFtSuEryXHfCjUXuXWsEi3PP7/I4usm.QnsIJaQOThFGmBZ2DwZ0'
> >>> sha512_crypt.verify('test', '$6$rounds=656000$Wgo04NdlW5Ut06a.$biRRaEnSxQWPC3L1KtNPKmwBn7h9LROP1cfFtSuEryXHfCjUXuXWsEi3PP7/I4usm.QnsIJaQOThFGmBZ2DwZ0')
> True
> ```

Ah. I see. If crypt is unavailable or gives unexpected result, it falls back to an internal implementation in the module:
https://foss.heptapod.net/python-libs/passlib/-/blame/branch/stable/passlib/handlers/sha2_crypt.py#L375

2024-02-06 15:15 UTC, bmeagherix approved these changes
> @bmeagherix my PR removes `crypt` module usage from [plugins/auth_/authenticate.py](https://github.com/truenas/middleware/blob/master/src/middlewared/middlewared/plugins/auth_/authenticate.py#L69)

My apologies.  Don't know what was wrong with me.

2024-02-06 15:20 UTC, themylogin commented
@anodos325 we use passlib in other modules as well

2024-02-08 16:40 UTC, closed without merging