Allow RDMA capable interfaces to be exposed for regular networking
truenas/middleware pull request #13289
Opened 2024-03-06 21:58 UTC by bmeagherix

When JBOF support was added, we added *all* RDMA interfaces to `rdma.interface.internal_interfaces`.  Instead only add those currently in use for JBOF purposes.

Likewise, in `rdma.get_link_choices` omit any interfaces that have been configured for general networking.

2024-03-06 21:58 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127697

2024-03-06 22:25 UTC, bmeagherix commented
@yocalebo I added `rdma.get_configured_interfaces`, but there could be an argument to move this into `interface.get_configured_interfaces` instead.  Any comment?

2024-03-08 12:39 UTC, yocalebo requested changes

2024-03-08 17:07 UTC, yocalebo approved these changes

2024-03-08 17:10 UTC, merged

2024-03-08 17:10 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.