NAS-127729 / 24.10 / Update nfs syslog filter test
truenas/middleware pull request #13297
Opened 2024-03-07 20:55 UTC by mgrimesix

### Problem
This test has been plagued with consistent failure because the system under test randomly stalls and delays the critical syslog messages.  The stall can be several minutes.
### Fix
Increase the timeout for this test.
Add more retries with increasing delay between them.  The expectation is to prevent unnecessary delay if the messages are output in a timely manner.

2024-03-07 20:55 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127729

2024-03-07 20:55 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127729

2024-03-09 01:47 UTC, bmeagherix requested changes
33 is a magic number sprinkled in a few places.  Make it defined once.

2024-03-26 18:13 UTC, closed without merging

2024-03-26 18:13 UTC, mgrimesix commented
This is going to require a very different approach.
Closing this PR.