Improve error handling for already in use PCI devices
truenas/middleware pull request #13603
Opened 2024-04-22 15:24 UTC by Qubad786

**Problem:**

An issue arises when the same PCI device is added to two virtual machines (VMs), and one of the VMs is already running. When the user attempts to start the second VM, QEMU raises an error indicating that the PCI device is already in use by another VM.

**Solution:**

To address this problem, validation for the PCI device has been updated. It now also considers whether the same PCI device is in use by another VM. If the PCI device is not in use by any other VM, it is marked as available for use or otherwise error out on middleware side that the device is already being used.

2024-04-22 15:24 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-123677

2024-04-22 15:28 UTC, yocalebo requested changes

2024-04-22 15:28 UTC, yocalebo commented on src/middlewared/middlewared/plugins/vm/devices/pci.py
> +        if not self.not_in_use_by_vm():
This is a double-negative which makes it pretty hard to follow what's actually being checked. I also think the name `not_in_use_by_vm()` is actually the inverse of what it's checking? It's actually checking if the device is IN USE by a vm? Either way, this is very confusing so we should rename/fix it.

2024-04-26 06:09 UTC, Migsi commented
Wouldn't it be better to just highlight in use devices instead of removing them from the list alltogether? I'm running a setup where I pass through the same GPU to a Windows and a Linux VM, which are running mutually exclusive. While obviously not done every day, having to stop either VM before being able to setup (not run) a second, thrid, fourth, etc. still seems quite a bit annoying to me.

2024-04-28 23:46 UTC, Qubad786 commented
@Migsi yes that is accurate so your case is still good to go ✅

2024-04-29 19:42 UTC, yocalebo approved these changes

2024-04-29 19:47 UTC, merged