Add ctypes wrapper for NSS operations
truenas/middleware pull request #13630
Opened 2024-04-29 19:05 UTC by anodos325

This allows us to do module-specific NSS operations and provide information to API users about whether the user is local, from AD, or from LDAP server.

The changes are necessary for providing user/group cache for UI / middleware purposes after switching from nslcd to sssd for LDAP integration.

2024-04-29 19:05 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128640

2024-04-29 21:10 UTC, bmeagherix requested changes

2024-04-29 21:10 UTC, bmeagherix commented on src/middlewared/middlewared/utils/nss/grp.py
> +        ctypes.POINTER(ctypes.c_int)
Same comment as for pwd.  Why is this this type?  Comment please.

2024-04-29 21:10 UTC, bmeagherix commented on src/middlewared/middlewared/utils/nss/grp.py
> +    NOTE: this calls thread-safe per-module variant of setgrent
thread-safe?  Calls `setgrent`.

2024-04-29 21:10 UTC, bmeagherix commented on src/middlewared/middlewared/utils/nss/grp.py
> +    NOTE: this calls thread-safe per-module variant of endgrent
Same comment wrt thread-safe.

2024-04-29 21:10 UTC, bmeagherix commented on src/middlewared/middlewared/utils/nss/grp.py
> +                results[mod.name] = entries
Same comment as for pwd.  Although, since there's no comment on `getgrall` we can't tell here what the intended behavior is! :-)

2024-04-29 21:19 UTC, mgrimesix requested changes
Possibly overlapping comments from Brian.

2024-04-30 12:16 UTC, anodos325 commented on src/middlewared/middlewared/utils/nss/pwd.py
> +        ctypes.POINTER(ctypes.c_int)
Yes, it's different when you query module directly. I expanded comments to show what arguments the NSS functions take.

2024-04-30 12:31 UTC, anodos325 commented on src/middlewared/middlewared/utils/nss/grp.py
> +GROUP_BUFLEN = 8096
It's an initial buffer length. IIRC that was the default in most FreeBSD applications. I've changed to make it dynamic.

2024-04-30 14:47 UTC, bmeagherix approved these changes
LGTM

2024-04-30 14:49 UTC, mgrimesix approved these changes

2024-04-30 14:54 UTC, merged

2024-04-30 14:54 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.