Add SSSD to pam configuration
truenas/middleware pull request #13632
Opened 2024-04-29 20:41 UTC by anodos325

This commit adds basic SSSD integration with our existing pam modules. Based on sample pam config provided by debian.

2024-04-29 20:41 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128645

2024-04-29 21:36 UTC, mgrimesix requested changes

2024-04-29 21:36 UTC, mgrimesix commented on src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
>              entries.append(super().pam_session(pam_path=self.pam_ldap, pam_control='optional'))
This should be pam_sss

2024-04-29 21:36 UTC, mgrimesix commented on src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
>              ldap_entry = super().pam_password(pam_path=self.pam_ldap, pam_args=ldap_args, success=1)
change to sssd entry?  Here and below.
e.g.
`sssd_entry = super().pam_password(pam_path=self.pam_sss, pam_args=ldap_args, success=1)`

2024-04-29 21:36 UTC, mgrimesix commented on src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
>              entries = [unix_entry, ldap_entry]
change to:
`entries = [unix_entry, sssd_entry]`

2024-04-29 21:55 UTC, mgrimesix reviewed
Updated my review.

2024-04-29 21:55 UTC, mgrimesix commented on src/middlewared/middlewared/etc_files/pam.d/pam.inc.mako
> +            self.pam_ldap = "pam_sss.so"
Hmm... it means a little more changes, but I think we should not use pam_ldap for pam_sss.

2024-04-30 14:58 UTC, mgrimesix approved these changes

2024-04-30 14:59 UTC, bmeagherix approved these changes

2024-04-30 15:10 UTC, merged

2024-04-30 15:10 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.