Fix Range validator args
truenas/middleware pull request #13705
Opened 2024-05-13 18:07 UTC by sonicaj

This commit fixes an issue where when we change max to max_ in middleware api for validators, this change was not addressed.

2024-05-13 18:07 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128590

2024-05-13 18:23 UTC, yocalebo commented
@sonicaj why is this a draft?

2024-05-13 18:32 UTC, yocalebo requested changes
This seems fundamentally broken. I think I see other areas in this file where it's using `max` for other schema classes. I don't understand why we're writing another abstraction layer on top of our schema classes because errors like these should have been caught at CI time on github. Not after the fact.

2024-05-13 19:33 UTC, sonicaj commented
@yocalebo that is the `max/min` app devs specify in `questions.yaml` - we internally changed our API to use `max_` instead. So it seems very weird to use `max_` in yaml file to outline maximum length, we internally changed it because it collided with python builtins. Also it would be very messy to have app devs switch to `max_` if we wanted to (i don't think we should), as older apps which app devs have not updated will no longer work and would be a decent change depending on the size of catalog.
I think we should have tests in place to catch this sooner, i'll write some and push them if that sounds good ?

2024-05-13 20:32 UTC, yocalebo commented
> @yocalebo that is the `max/min` app devs specify in `questions.yaml` - we internally changed our API to use `max_` instead. So it seems very weird to use `max_` in yaml file to outline maximum length, we internally changed it because it collided with python builtins. Also it would be very messy to have app devs switch to `max_` if we wanted to (i don't think we should), as older apps which app devs have not updated will no longer work and would be a decent change depending on the size of catalog. I think we should have tests in place to catch this sooner, i'll write some and push them if that sounds good ?

Yep agree, tests would be a good start!

2024-05-14 23:49 UTC, yocalebo commented
Are you sure this fixes all the failures? On lines 108, 109 I still see references to `min` and `max`

2024-05-15 01:46 UTC, sonicaj commented
> Are you sure this fixes all the failures? On lines 108, 109 I still see references to `min` and `max`

@yocalebo yes I am and i have added a unit test as well to outline that. Those `min/max` references are to the values in `questions.yaml` and not our schema so we are safe on that end

2024-05-15 01:48 UTC, yocalebo approved these changes

2024-05-15 11:16 UTC, merged

2024-05-15 11:16 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.