Remove ability to configure swap from the API
truenas/middleware pull request #13726
Opened 2024-05-15 14:15 UTC by Qubad786

## Context

We now don't try to configure or manage swap and finally now we are removing it from our API as well so consumers won't be able to configure this anymore via our API.

2024-05-15 14:15 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128889

2024-05-15 14:21 UTC, sonicaj approved these changes

2024-05-15 15:21 UTC, yocalebo requested changes
I think this is the perfect opportunity to remove the `create_swap` references through the API. Can you please go ahead and do that in this PR since you're making changes to the db.

2024-05-24 18:02 UTC, yocalebo approved these changes

2024-05-27 13:36 UTC, merged

2024-05-27 13:36 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.