Do not listen on `0.0.0.0:6000`
truenas/middleware pull request #13830
Opened 2024-06-03 10:23 UTC by themylogin

2024-06-03 10:23 UTC, themylogin commented
time 1:00

2024-06-03 10:23 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127971

2024-06-03 16:53 UTC, Qubad786 approved these changes

2024-06-03 17:17 UTC, yocalebo requested changes

2024-06-03 17:17 UTC, yocalebo commented on src/middlewared/middlewared/plugins/system_general/update.py
> +        Determines whether we are waiting user to check in the applied UI settings changes before they are rolled
Superfluous changes?

2024-06-03 21:27 UTC, yocalebo approved these changes

2024-06-03 22:36 UTC, yocalebo requested changes
Actually we can add a test that makes sure we're not listening on any external interface on port 6000

2024-06-06 11:37 UTC, yocalebo approved these changes

2024-06-06 11:39 UTC, merged

2024-06-06 11:39 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.