Fix netdata spamming logs
truenas/middleware pull request #13860
Opened 2024-06-07 16:19 UTC by Qubad786

## Problem
We were seeing logs being continuously written to, after investigation, we found that only the UPS plugin of netdata is causing issues. When UPS is not configured, the failed `upsc -l` command returns an error, spamming the Netdata logs and causing the log file size to increase continuously.

## Solution
Modify the Netdata plugin to avoid executing the `upsc` command when `upsmon` process is not running. Additionally, disable access logs since only the `errors.log` is used for debugging, thereby preventing unnecessary log file growth.

2024-06-07 16:20 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129384

2024-06-07 17:48 UTC, anodos325 commented on src/middlewared/middlewared/etc_files/netdata/netdata.conf.mako
> +    access = off
tabs vs spaces?

2024-06-07 17:58 UTC, yocalebo requested changes
Again sorry, but no. We're shell'ing out every 1/2 seconds for this stuff. We can't do this on our enterprise systems so we're going to have to come up with a better solution. If that means we have to disable UPS reporting for now, then so be it.

2024-06-11 10:06 UTC, anodos325 approved these changes

2024-06-13 13:38 UTC, merged

2024-06-13 13:39 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.