Change download method from call to call_with_audit.
truenas/middleware pull request #13917
Opened 2024-06-21 23:46 UTC by mgrimesix

The method calls that are part of `core.download` are not being audited.

The parameters for `core.download` include 
When adding auditing of the audit subsystem it was discovered that method calls via `core.download` were not being audited.
This PR converts `core.download` to include auditing.

2024-06-21 23:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129695

2024-06-21 23:47 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-129695

2024-06-23 20:23 UTC, themylogin requested changes
Can you add a test for this please?

2024-06-24 14:43 UTC, mgrimesix commented
CI tests are going to follow.  
We need a download that includes a call to an audited subsystem.
This issue was discovered in the new CI tests of the changes for adding auditing of the audit subsystem.  This particular change _was_ going to be part of that PR, but it was requested I separate it out.

2024-06-24 14:58 UTC, themylogin approved these changes

2024-06-24 15:21 UTC, merged

2024-06-24 15:21 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.