NAS-130362 / 24.10 / Add `system.vendor.is_vendored` endpoint
truenas/middleware pull request #14117
Opened 2024-07-31 17:24 UTC by creatorcary

Basic endpoint that checks for the existence (not the contents) of a `/data/.vendor` file indicating that the system is a vendored build.

Passing tests: http://jenkins.eng.ixsystems.net:8080/job/master/job/api_tests/1754/

2024-07-31 17:30 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130362

2024-07-31 17:32 UTC, bmeagherix requested changes

2024-07-31 17:32 UTC, bmeagherix commented on src/middlewared/middlewared/api/v25_04_0/vendor.py
> +    result: None
Shouldn't this be `bool` ?

2024-07-31 17:39 UTC, creatorcary commented on src/middlewared/middlewared/api/v25_04_0/vendor.py
> +    result: None
Yep, somehow I completely missed that.

2024-07-31 17:41 UTC, bmeagherix approved these changes

2024-07-31 18:51 UTC, aiden3c approved these changes

2024-08-01 01:07 UTC, merged

2024-08-01 01:08 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.