Remove legacy pool.dataset.permission endpoint
truenas/middleware pull request #14170
Opened 2024-08-08 15:28 UTC by anodos325

This functionality has been superseded by filesystem ACL and permissions endpoints since TrueNAS 12. Endpoint is no longer used by the webui and so it is safe to remove.

2024-08-08 15:28 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130507

2024-08-09 15:20 UTC, yocalebo approved these changes

2024-08-09 15:31 UTC, mgrimesix approved these changes

2024-08-09 15:51 UTC, bmeagherix commented on src/middlewared/middlewared/plugins/pool_/dataset_quota_and_perms.py
> -        Dict(
FWIW, removing all this code means that now this file has many imported but not used flake8 warnings.
- `errno`
- `Bool`
- `OROperator`
- `UnixPerm`
- `CallError`

2024-08-09 15:53 UTC, bmeagherix commented on tests/api2/test_347_posix_mode.py
> +    server_mode = f"{stat.S_IMODE(mode):03o}"
`get_mode_octal` is duplicated (sort of) below.

2024-08-09 18:53 UTC, bmeagherix requested changes

2024-08-09 18:53 UTC, bmeagherix commented on tests/api2/test_347_posix_mode.py
> +    server_mode = f"{stat.S_IMODE(mode):03o}"
Need to return the `server_mode`.

2024-08-09 18:58 UTC, anodos325 commented on tests/api2/test_347_posix_mode.py
> +    server_mode = f"{stat.S_IMODE(mode):03o}"
Sigh. Good eye.

2024-08-09 18:59 UTC, bmeagherix approved these changes

2024-08-09 19:42 UTC, merged

2024-08-09 19:43 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.