Fix zpool status for reporting used spare disks correctly
truenas/middleware pull request #14262
Opened 2024-08-19 10:42 UTC by Qubad786

## Problem

`zpool.status` was not properly reporting path for disk properly when a spare had replaced a data disk.

## Solution

With changes being introduced in https://github.com/truenas/py-libzfs/pull/276, we now make sure path is reported properly. There have been some other changes introduced as well where we add vdev type key to the object as well because for example spare replacing a disk means that the same entry will be present in data vdev and spare vdev and they should be reported properly.
In terms of performance, i was seeing `0.063 seconds ` for `zpool.status` endpoint and with latest changes the average speed is `0.060 seconds`.

2024-08-19 10:43 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-127511

2024-08-27 14:34 UTC, themylogin commented
Can we have integration tests for this?

2024-09-03 16:54 UTC, yocalebo requested changes
`zpool status` will resolve the vdev devices so we need to remove the `resolve_*` methods accordingly.

If `real_paths` is true, we can use `-PL` otherwise, we can just use `-P`.

`-P` will give full path to device (i.e. `/dev/disk/by-partuuid/**`)
`-PL` will give full path to real device (i.e. `/dev/sda1`)

2024-09-03 16:55 UTC, yocalebo approved these changes
No, actually, we'll leave it as is for now since this is going into RC.1

2024-09-04 19:15 UTC, merged

2024-09-04 19:16 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.