Make sure we delete any app volume mount datasets created on app install failure
truenas/middleware pull request #14544
Opened 2024-09-19 16:34 UTC by sonicaj

This PR adds changes to remove any app volume mount datasets created during installation in the event installation process failed for whatever reason. We are picky on this end and make sure we only remove them if the app volume dataset didn't exist before as when a user deletes an app, it's optional for him/her to remove the app volume mounts datasets and we don't want them nuked if a user installs an app with the same name and app install fails for whatever reason.

2024-09-19 16:35 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130966

2024-09-19 17:57 UTC, Dremor commented
I have a question : Will we be able to remove ti ix-volumes if we remove an app without choosing to remove the ix-volume at that time ? I'm currently stuck with multiple ix-volumes I cannot remove, and would like to be able to remove them.

2024-09-20 12:31 UTC, yocalebo requested changes

2024-09-20 12:31 UTC, yocalebo commented on src/middlewared/middlewared/plugins/apps/crud.py
> +    def remove_failed_resources(self, app_name, version, remove_ds=False):
This for loop is wicked complicated for no real reason. Please simplify this so it's easier for future developers to read/maintain.

2024-09-20 17:44 UTC, Qubad786 commented on src/middlewared/middlewared/plugins/apps/crud.py
> +            with contextlib.suppress(Exception):
Maybe at least log this so we know why it failed if it did as the dataset should exist based on above func call

2024-09-20 17:56 UTC, Qubad786 approved these changes

2024-09-20 18:17 UTC, yocalebo approved these changes

2024-09-20 18:20 UTC, merged

2024-09-20 18:21 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-09-20 18:28 UTC, sonicaj commented
> I have a question : Will we be able to remove ti ix-volumes if we remove an app without choosing to remove the ix-volume at that time ? I'm currently stuck with multiple ix-volumes I cannot remove, and would like to be able to remove them.

@Dremor we would be adding some changes for FangTooth on this end so users can remove any ix-volumes which are not associated with any installed app.