Convert acme_protocol to new api style
truenas/middleware pull request #14600
Opened 2024-10-01 14:28 UTC by creatorcary

Passing: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1068/

2024-10-01 14:28 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131393

2024-10-01 14:44 UTC, themylogin requested changes

2024-10-01 14:44 UTC, themylogin commented on src/middlewared/middlewared/api/v25_04_0/acme_protocol.py
> +    data: DNSAuthenticatorCreate
In the original code this variable is called `dns_authenticator_create`

2024-10-02 13:35 UTC, creatorcary commented on src/middlewared/middlewared/api/v25_04_0/acme_protocol.py
> +    id: int
This can replace `ENTRY` right?

2024-10-02 13:41 UTC, themylogin commented on src/middlewared/middlewared/api/v25_04_0/acme_protocol.py
> +    id: int
ENTRY is not used for new-style API

2024-10-03 20:04 UTC, themylogin requested changes

2024-10-03 20:04 UTC, themylogin commented on src/middlewared/middlewared/api/v25_04_0/acme_protocol.py
> +class DNSAuthenticatorUpdate(DNSAuthenticatorCreate):
You should include `metaclass=ForUpdateMetaclass` here (as we do for other update schemas) so that all fields become not required

2024-10-04 13:44 UTC, themylogin approved these changes

2024-10-04 16:05 UTC, merged

2024-10-04 16:05 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.