Use unique disk identifier for retrieving/maintaining disk stats
truenas/middleware pull request #14610
Opened 2024-10-02 16:12 UTC by Qubad786

## Problem

Netdata uses disk names to store disk statistics in it's database. We can configure it as such that it uses disk identifier to retrieve but that does not help because in the database they are stored with disk names which means after reboots or hardware changes, the data is not going to remain consistent if disk names changed.

## Solution

After much investigation we decided to write our own disk stats plugin which uses procfs similar to netdata to retreive disk statistics but in this case we are using disk identifiers to store/retrieve them in netdata database. The identifier being used to store the stats is similar to the logic we have in place to uniquely identify our own disks.

CI Run: http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1119/

2024-10-02 16:12 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-130009

2024-10-03 14:51 UTC, mgrimesix commented on src/middlewared/middlewared/plugins/enclosure.py
> +from middlewared.utils.disks import DISKS_TO_IGNORE
Not used.

2024-10-03 15:02 UTC, mgrimesix commented on src/middlewared/middlewared/utils/disks.py
> +        if type(value) == bytes:
flake8:  use 'is' not '==' for type check

2024-10-14 14:56 UTC, yocalebo requested changes

2024-10-14 14:56 UTC, yocalebo commented on src/middlewared/middlewared/utils/disk_stats.py
> +            disk_stats_content = f.read()
Let's not read the entire contents of this file into memory. Instead we should iterate over it. (i.e.
```
with open('/proc/diskstats', 'r') as f:
    for line in f:
        parts = line.strip().split()
        if len(parts) < 14 or parts[2] not in available_disks:
            continue

2024-10-17 20:31 UTC, mgrimesix approved these changes
Approving, but might want to wait for Caleb's review.

2024-10-18 00:47 UTC, yocalebo approved these changes

2024-10-18 10:08 UTC, merged

2024-10-18 10:09 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.