Fix pool deletion with active NFS shares.
truenas/middleware pull request #14692
Opened 2024-10-15 18:59 UTC by mgrimesix

Deleting a pool fails if the pool has active NFS shares.

The fix for this is:  Add deletion attachment delegate for NFS shares. 

This PR also includes a CI test for this condition.

Passing CI test can be found [here](http://jenkins.eng.ixsystems.net:8080/job/tests/job/api_tests/1354/).

2024-10-15 19:00 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131570

2024-10-15 23:29 UTC, bmeagherix requested changes

2024-10-15 23:29 UTC, bmeagherix commented on src/middlewared/middlewared/plugins/nfs_/fs_attachment_delegate.py
> +            await self.middleware.call('sharing.nfs.delete', attachment['id'])
I _think_ we still need to include `remove_alert` inside the `for` loop.
```
        for attachment in attachments:
            await self.middleware.call('sharing.nfs.delete', attachment['id'])
            await self.remove_alert(attachment)
```

2024-10-16 00:23 UTC, mgrimesix commented
The reproduction and fix are more slippery than first thought.   Changing to WIP for more investigation.

2024-10-22 19:56 UTC, bmeagherix approved these changes
LGTM

2024-10-22 20:05 UTC, merged

2024-10-22 20:05 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.