`pool.replace` `preserve_description`
truenas/middleware pull request #14735
Opened 2024-10-21 11:45 UTC by themylogin

2024-10-21 11:46 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-131821

2024-10-21 11:46 UTC, themylogin commented
time 0:30

2024-10-21 11:50 UTC, yocalebo approved these changes

2024-10-21 11:51 UTC, yocalebo requested changes

2024-10-21 11:51 UTC, yocalebo commented on src/middlewared/middlewared/plugins/pool_/replace_disk.py
> +        Bool('preserve_description', default=True),
Actually, can we add an integration test?

2024-10-24 18:04 UTC, themylogin commented
time 1:00

2024-10-25 12:09 UTC, merged

2024-10-25 12:09 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.