Introduce job `read_roles` that will allow users to access jobs that …
truenas/middleware pull request #14814
Opened 2024-10-30 13:14 UTC by themylogin

…were not started by them

2024-10-30 13:14 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132031

2024-10-30 13:14 UTC, themylogin commented
http://jenkins.eng.ixsystems.net:8080/job/master/job/custom/653/

2024-10-30 13:14 UTC, themylogin commented
time 3:00

2024-10-30 13:23 UTC, anodos325 commented on src/middlewared/middlewared/service/decorators.py
> +        and download its logs even if the job was launched by another user or by the system.
We should also mention impact on `core.job_wait` and that by default users are able to read their own jobs. E.g. try to convince developer not to populate unless necessary.

2024-10-30 13:40 UTC, yocalebo requested changes
We also need a description in the body of the PR explaining why this is needed and what problem it solves.

2024-10-30 13:59 UTC, themylogin commented
@yocalebo done

2024-10-30 14:43 UTC, yocalebo commented
The api test run failed during the building of middlewared package.

2024-10-30 14:46 UTC, anodos325 approved these changes

2024-10-30 14:47 UTC, anodos325 commented
Approved pending fix for whatever crashed in build :)

2024-10-31 07:16 UTC, themylogin commented
time 1:00

2024-10-31 07:16 UTC, themylogin commented
@yocalebo API tests succeeded

2024-10-31 09:15 UTC, yocalebo approved these changes

2024-10-31 09:41 UTC, merged

2024-10-31 09:41 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-132031 is targeted to the following versions which have not received their corresponding PRs: 24.10.1

2024-10-31 09:41 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-10-31 09:50 UTC, themylogin commented
backport