Fix bugs in ACME DNS auth service and convert schemas to new api style
truenas/middleware pull request #14855
Opened 2024-11-02 16:02 UTC by sonicaj

This PR adds following changes:

1. Refactors some code to reflect new guidelines we have in place for defining pydantic models of services
2. Fixes some bugs with existing models with key mismatches and args handling
3. Convert authenticator schemas to use new api style pydantic models

2024-11-02 16:02 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132196

2024-11-02 16:03 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132196

2024-11-04 13:29 UTC, yocalebo requested changes

2024-11-04 13:29 UTC, yocalebo commented on src/middlewared/middlewared/api/base/types/base/path.py
> +from pathlib import Path
This entire file can be removed and replaced with the built-in `FilePath` builtin pydantic annotation. Please use that instead.

2024-11-04 15:16 UTC, creatorcary commented
Why are we adding `validate_credentials` to our versioned api? (Are they public endpoints?)

2024-11-04 15:47 UTC, sonicaj commented
@creatorcary they are not middleware endpoints at all, it is just making use of the accepts/returns model with pure python as these are not services themselves, they will never get collected by middleware. @themylogin do you think we should have another util which `api_method` can call and that can hold this logic ?

2024-11-05 10:23 UTC, themylogin commented
@sonicaj it’s better to have all models be accepted immediately by API methods. The reason is: if models change between API definitions, who will convert them? Please, try to fit these models into the function calls themselves using a discriminator (that’s already done for new VMs, and that’s what I’ll soon do for alerts and cloud syncs).

2024-11-06 08:40 UTC, themylogin approved these changes
Excellent, thank you!

2024-11-06 10:53 UTC, yocalebo approved these changes

2024-11-06 12:00 UTC, merged

2024-11-06 12:00 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.