NAS-132712 / 25.04 / Fix alert text format for Mattermost.
truenas/middleware pull request #15025
Opened 2024-11-24 16:39 UTC by nicodemusjls

Mattermost does not render html code sent in
messages. This edit removes/replaces html code from
the message text and adopts the markdown formatting
used by Mattermost.

2024-11-24 17:01 UTC, yocalebo requested changes
Thanks for the PR but this isn't the right fix. Looking at this a bit closer, the `ThreadedAlertService`'s `_format_alerts` method is incorrect. If you look at the `AlertService` class there is a class attribute called `html` which is set to `False` by default. This means, the alert message should not be sending html by default. The proper fix is to fix the `_format_alerts` method in the `ThreadedAlertService` class. If you look at the `AlertService` base classes `_format_alert` method, you should see the discrepancy.

2024-11-24 18:05 UTC, nicodemusjls reviewed
I appreciate your feedback. I'm not sure why ThreadedAlertService isn't  removing html formatting like AlertService does. However, your response was perfect in that it got me looking deeper. Now, I'm following the approach used in the Slack, Telegram, and other alert service pieces, I've used html2text directly. This way the solution matches exactly what has been implemented elsewhere.

2024-11-24 18:09 UTC, yocalebo approved these changes
Cool, thanks for the PR!

2024-11-24 18:10 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132712

2024-11-25 13:46 UTC, merged

2024-11-25 13:46 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.