Properly retrieve vms in dataset details
truenas/middleware pull request #15134
Opened 2024-12-05 19:13 UTC by Qubad786

## Problem

With recent shift to pydantic models for VM plugins, we had changed how we were retrieving vm devices which resulted in `pool.dataset.details` not working when disk based vm devices were being used.

## Solution

Properly retrieve vms which are consuming datasets when retrieving dataset details.

2024-12-05 19:13 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132905

2024-12-05 19:17 UTC, yocalebo requested changes
We need to figure out how to do this without adding another `vm.query` call. We've already got a ticket about this method taking 8-10 seconds to return and this won't help it in any way.

2024-12-05 19:17 UTC, themylogin commented on src/middlewared/middlewared/api/v25_04_0/vm.py
> +    cpu_mode: Literal['CUSTOM', 'HOST-MODEL', 'HOST-PASSTHROUGH'] = 'CUSTOM'
Is this desired?

2024-12-05 19:41 UTC, Qubad786 commented on src/middlewared/middlewared/api/v25_04_0/vm.py
> +    cpu_mode: Literal['CUSTOM', 'HOST-MODEL', 'HOST-PASSTHROUGH'] = 'CUSTOM'
Yes

2024-12-09 11:07 UTC, yocalebo approved these changes

2024-12-09 11:07 UTC, merged

2024-12-09 11:08 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.