Add `cloud_backup.abort` test
truenas/middleware pull request #15210
Opened 2024-12-13 22:01 UTC by creatorcary

This is the only cloud_backup endpoint not covered by our api tests yet.

2024-12-13 22:02 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-132728

2024-12-13 23:58 UTC, mgrimesix commented on tests/api2/test_cloud_backup.py
> +    ssh(f"touch /mnt/{cloud_backup_task.local_dataset}/testfile")
Do we validate that `testfile` was successfully backed up?

2024-12-13 23:58 UTC, mgrimesix approved these changes
Approve with comment.

2024-12-16 12:35 UTC, themylogin requested changes

2024-12-16 12:55 UTC, creatorcary commented on tests/api2/test_cloud_backup.py
> +    call("cloud_backup.sync", task_id, {"dry_run": True})
We don't actually need to backup an empty file. We could probably set `dry_run=True` for most of the tests in this module without consequence.

2024-12-16 12:57 UTC, themylogin commented on tests/api2/test_cloud_backup.py
> +    call("cloud_backup.sync", task_id, {"dry_run": True})
If we don't perform any writes to the backup backend, what are we testing here then?

2024-12-16 12:59 UTC, creatorcary commented on tests/api2/test_cloud_backup.py
> +    call("cloud_backup.sync", task_id, {"dry_run": True})
Hmm I guess we do need to make sure it's creating a lock on the repository in this case

2024-12-16 13:09 UTC, themylogin commented
@creatorcary this still does not test anything. The cloud backup task is aborted shortly after its started, `restic` might not have even started yet. We need to actually ensure we've started backing up something huge. Having a transfer speed limiter just for testing will be a huge help to make this process more deterministic.

2024-12-18 20:05 UTC, themylogin commented on tests/api2/test_cloud_backup.py
> +        time.sleep(0.5)
I would say even 0.1

2024-12-18 20:05 UTC, themylogin approved these changes
Thank you!

2024-12-18 20:14 UTC, merged

2024-12-18 20:14 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.