Allow not retrieving user props for datasets
truenas/middleware pull request #15287
Opened 2024-12-31 11:08 UTC by Qubad786

## Context

There is no way currently to not retrieve user properties when retrieving dataset details from `pool.dataset` namespace, hence changes have been added to make that configurable.

2024-12-31 11:09 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-133056

2024-12-31 13:23 UTC, yocalebo reviewed
We can write a trivial test for this

2024-12-31 15:50 UTC, creatorcary approved these changes
Looks good

2025-01-01 16:11 UTC, yocalebo requested changes

2025-01-01 16:11 UTC, yocalebo commented on tests/api2/test_pool_dataset_user_props.py
> +def test_pool_dataset_query_default_user_props():
This test is unnecessary since you're validating same logic in the test below this.

2025-01-02 13:44 UTC, yocalebo approved these changes

2025-01-02 15:01 UTC, merged

2025-01-02 15:01 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.