Allow retrieving pod / container logs from a chart release
truenas/middleware pull request #6384
Opened 2021-02-06 15:54 UTC by sonicaj

2021-02-08 10:48 UTC, themylogin commented
@sonicaj can they be multi-megabyte files that will have zero sense to be displayed in browser? If so, we can use our job streaming facilities.

2021-02-09 12:19 UTC, themylogin requested changes

2021-02-09 12:19 UTC, themylogin commented on src/middlewared/middlewared/plugins/chart_releases_linux/resources.py
> +    @job(lock='dataset_export_keys', pipes=['output'])
Why `lock='dataset_export_keys'`?

2021-02-09 12:19 UTC, themylogin commented on src/middlewared/middlewared/plugins/chart_releases_linux/resources.py
> +                shutil.copyfileobj(f, job.pipes.output.w)
You may just write directly to the pipe.

There is little point in piping `k8s.pod.get_logs` result since it is already loaded to the RAM entirely

2021-02-09 12:52 UTC, themylogin requested changes

2021-02-09 12:52 UTC, themylogin commented on src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
> +            return await context['core_api'].read_namespaced_pod_log(
Don't we have any sort of streaming API here? I don't like the entire log being loaded into RAM

2021-02-09 12:52 UTC, themylogin commented on src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
> +                    self.send_event('ADDED', fields={'data': event})
How much of the existing logs will be streamed here?

2021-02-16 17:14 UTC, william-gr approved these changes

2021-02-16 19:30 UTC, themylogin approved these changes

2021-02-16 19:30 UTC, themylogin commented on src/middlewared/middlewared/plugins/kubernetes_linux/pods.py
> +class KubernetesPodLogsFileFollowTailEventSource(EventSource):
What `FileFollowTail` has to deal with it?

2021-02-17 10:07 UTC, merged