Add validation for network cidr being specified for kubernetes
truenas/middleware pull request #6457
Opened 2021-02-20 15:59 UTC by sonicaj

This PR introduces following changes:

1) Do not return `vnetX` interface in `interface.query`
2) Do a best effort to check if cluster/service CIDR are already being used by the system.
3) Do not allow cluster/service CIDR to be similar
4) Service/Cluster CIDR must not overlap

2021-02-22 16:00 UTC, yocalebo approved these changes

2021-02-24 20:04 UTC, william-gr commented on src/middlewared/middlewared/plugins/kubernetes_linux/update.py
> +                ipaddress.ip_network('10.0.0.0/8', False).subnets(8)
Add 192.168 too?

2021-02-26 13:24 UTC, sonicaj commented
retest this please

2021-03-03 10:44 UTC, themylogin requested changes

2021-03-03 10:44 UTC, themylogin commented on src/middlewared/middlewared/plugins/kubernetes_linux/update.py
> +        if data['cluster_cidr'] and data['cluster_cidr'] == data['service_cidr']:
Why do we need this check if there is an `overlaps` check below?

2021-03-03 10:44 UTC, themylogin commented on src/middlewared/middlewared/plugins/kubernetes_linux/update.py
> +            verrors.add(f'{schema}.cluster_cidr', 'Value cannot be similar to service CIDR.')
I, as an user, am not sure what does `similar` mean here

2021-03-03 18:02 UTC, william-gr approved these changes

2021-03-05 11:23 UTC, themylogin approved these changes

2021-03-05 11:25 UTC, merged