Use SPICE instead of VNC for remote display device in VMs
truenas/middleware pull request #6516
Opened 2021-03-02 13:48 UTC by sonicaj

2021-03-02 16:13 UTC, william-gr reviewed
The idea was to provide both, SPICE and VNC

2021-03-03 10:39 UTC, themylogin requested changes

2021-03-03 10:39 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/devices/display.py
> +        Str('resolution', enum=[
Should we have `resolution_choices` API method?

2021-03-03 10:39 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/devices/display.py
> +        get_params = f'?{"&".join(params)}' if params else ''
Should we use `urllib.parse.urlencode`?

2021-03-03 10:39 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/devices/display.py
> +                f'password={attrs["password"]}' if attrs.get('password') else None,
What if `password` contains `,`?

2021-03-03 10:39 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/devices/display.py
> +            if self.middleware:
Why can there be two use cases?

2021-03-04 13:57 UTC, themylogin approved these changes

2021-03-04 14:51 UTC, merged