Initial protocol testing for SMB using pylibsmb
truenas/middleware pull request #6543
Opened 2021-03-04 20:49 UTC by anodos325

Pylibsmb gives more fine-grained control over the SMB operations
performed on the server. Initial commit sets framework for doing these
additional tests as well as implements setting DOS modes through SMB1/2 CREATE.

2021-03-04 20:51 UTC, anodos325 commented
Note: this change will require net/samba412 (or some recent samba) to be installed on the server performing the tests
Minimal smb.conf (or smb4.conf) on the API testing server will be:
```
[global]
client min protocol = NT1
```
To allow python binding to perform SMB1 connections.

2021-03-04 20:52 UTC, anodos325 commented
Future commits will expand functionality for SMB1/2 tests to include shadow copies and alternate data streams.

2021-03-04 20:58 UTC, william-gr approved these changes

2021-03-09 19:18 UTC, ericbsd requested changes

2021-03-09 19:18 UTC, ericbsd commented on tests/api2/smb_protocol.py
> +# Author: Eric Turgeon
Should remove this or change the name I did not write the code.

2021-03-09 19:27 UTC, ericbsd approved these changes
LGTM

2021-03-09 19:27 UTC, merged