PoolDatasetService.do_create: skip children lookups on parent datasets
truenas/middleware pull request #6675
Opened 2021-03-25 05:50 UTC by rkojedzinszky

Backport of #6655

2021-04-03 08:50 UTC, rkojedzinszky commented on src/middlewared/middlewared/plugins/pool.py
> +        parent_ds = parent_ds[0]
That is not allowed, '/' is required in dataset name in a few lines above.

2021-04-03 08:54 UTC, pep8speaks commented
Hello @rkojedzinszky! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/middlewared/middlewared/plugins/pool.py`](https://github.com/truenas/middleware/blob/dd1c9bc01bc44726ff3e89071ba304c12f07f71d/src/middlewared/middlewared/plugins/pool.py):

> [Line 2915:17](https://github.com/truenas/middleware/blob/dd1c9bc01bc44726ff3e89071ba304c12f07f71d/src/middlewared/middlewared/plugins/pool.py#L2915): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2021-04-03 21:36 UTC, sonicaj commented on src/middlewared/middlewared/plugins/pool.py
> +        parent_ds = parent_ds[0]
Yes that is not allowed but it would have errored out with a traceback instead of validation error.

2021-04-03 21:37 UTC, sonicaj commented
@rkojedzinszky can you please address the pep8 concern when you have some time ? Thank you

2021-07-13 14:47 UTC, sonicaj requested changes

2021-07-13 14:47 UTC, sonicaj commented on src/middlewared/middlewared/plugins/pool.py
> +        parent_ds = parent_ds[0]
@rkojedzinszky can you please do `verrors.check()` at the L2920 as in that case if there are any other validation errors retrieved from `__common_validation`, they could be raised as well and this concern would be addressed too.

2021-07-13 14:47 UTC, sonicaj commented on src/middlewared/middlewared/plugins/pool.py
> +        parent_ds = parent_ds[0]
Also if `parent` is empty, this would still error out - so the above comment should cater to that as well.

2021-07-13 14:47 UTC, sonicaj commented on src/middlewared/middlewared/plugins/pool.py
> +                'zfs.dataset.query', zfsfilters, {'extra': extra})
Let's please not pass the complete `extra` payload to `zfs.dataset.query` as there are configuration knobs there which can potentially cause further bugs/issues as they can alter the output received from the internal service. I suppose you want `recursive` to be configurable, in this case let's please just add `recursive` to the extra argument like we were doing for `flat`

2021-07-16 04:39 UTC, rkojedzinszky commented
Superseeded by https://github.com/truenas/middleware/pull/6955

2021-07-16 04:39 UTC, closed without merging