Allow retrieving catalog data partially
truenas/middleware pull request #6957
Opened 2021-06-06 09:28 UTC by sonicaj

As community usage has grown, we are seeing lots of trains with a decent number of applications with decent number of versions in a catalog, this results in middleware taking considerable amount of time to reading the data and sending it to the UI. Even with caching, we get slow at json dumping/loading which impacts UI performance.

This PR intends to introduce the following changes:
1) Allow retrieving information of some specific trains only
2) Add `latest_version` key to item level payload so that consumer is able to know the latest healthy item version without going through the payload
3) Allow skipping retrieving versions of an item which helps improve performance for json dump/load operations
4) Introduce a new endpoint to retrieve version details of an item specifically without querying up everything

2021-06-06 09:28 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-110929

2021-06-07 11:15 UTC, themylogin requested changes

2021-06-07 11:15 UTC, themylogin commented on src/middlewared/middlewared/plugins/catalogs_linux/items.py
> +            Bool('skip_retrieving_versions', default=False),
Can we make it `Bool('retrieve_versions', default=True),` to avoid double negative?

2021-06-07 14:05 UTC, Ornias1993 commented
On top of `4.` it might be worthwhile to do the same for catalogs:
- Store a basic summary for each train (apps, last versions, icon urls, maybe health), storing on refresh
- Fetch this basic summary when loading the Apps UI, instead of actually requesting data for individual Apps.
- Maybe cache this on the UI client, with a incremental and purge on refresh.

Afaik thats a more efficient/quicker way of getting this basic information into the apps page.

2021-06-07 14:17 UTC, sonicaj commented
@Ornias1993 it's already happening like that right now :)

2021-06-07 14:19 UTC, Ornias1993 commented
> @Ornias1993 it's already happening like that right now :)

You're right... I could've just spend the time to look at the code and not just your summary >.<
```
    @accepts(
        Str('item_name'),
        Dict(
            'item_version_details',
            Bool('cache', default=True),
            Str('catalog', required=True),
            Str('train', required=True),
        )
    )
```

#FaceHitsWall

2021-06-07 17:46 UTC, rick-mesta commented
@themylogin: can't quite decipher if the issue you raised got resolved... would you mind taking another look and give a 👍🏼 or 👎🏼 ?

2021-06-07 17:59 UTC, themylogin approved these changes

2021-06-07 18:00 UTC, rick-mesta commented
Thx Vlad 🎉

2021-06-07 18:01 UTC, merged