Remote syslog server is overloaded alert
truenas/middleware pull request #7009
Opened 2021-06-10 17:32 UTC by themylogin

2021-06-10 17:32 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-107662

2021-06-10 17:33 UTC, themylogin commented on src/middlewared/middlewared/plugins/alert.py
> +        Text('formatted', null=True),
@sonicaj I suppose we now have middleware failing to return strings with length > 1024.

2021-06-10 17:44 UTC, yocalebo requested changes
1. This doesn't take into account the remote syslog connection on HA systems.
2. This request originated in September of 2020 by @anodos325. I'd like to know why this request came in the first place and if this is still even a valid request.

2021-06-11 12:26 UTC, themylogin commented
@yocalebo you're right, I forgot about HA syslog.

I'll wait with fixing this until the idea itself gets reviewed.

2021-07-06 19:38 UTC, yocalebo commented
Spoke with @anodos325 offline and this can be closed as the request is no longer valid.

2021-07-06 19:38 UTC, closed without merging