dont overwrite default gateway when we have one from dhclient
truenas/middleware pull request #7116
Opened 2021-07-07 13:07 UTC by yocalebo

If no default gateway has been specified by the end-user and we have one from `dhclient` then we do not need to manually install that gateway into the routing table. `dhclient` handles that for us so simply return in this scenario.

2021-07-07 13:07 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111324

2021-07-07 13:53 UTC, rick-mesta approved these changes
you fooled me 😁

2021-07-07 14:01 UTC, sonicaj requested changes

2021-07-07 14:01 UTC, sonicaj commented on src/middlewared/middlewared/plugins/network.py
> +                        if ipv4_gateway:
If we do not want to proceed further, is the complete if conditional required starting at L2322 ?

2021-07-07 14:01 UTC, sonicaj commented on src/middlewared/middlewared/plugins/network.py
> +                            return
We will not remove a gateway which is not in database but is configured, so this would be change of behavior ?

2021-07-07 14:01 UTC, sonicaj commented on src/middlewared/middlewared/plugins/network.py
> +                            return
Also ipv6 gateway would be ignored completely

2021-07-07 20:08 UTC, yocalebo commented
@sonicaj I truly do not want to figure out all the race conditions since we seem to be completely ignoring the default gateway that gets installed by `dhclient`. Instead I'll just catch this specific failure condition and make a comment on why this can occur.

2021-07-08 08:33 UTC, sonicaj commented on src/middlewared/middlewared/plugins/network.py
> +                        pass
Let's please log this at least for scenarios where the race condition does not hold and we have a gateway configured already which cannot be added in the current system network state.

2021-07-08 12:01 UTC, sonicaj commented on src/middlewared/middlewared/plugins/network.py
> +                    self.logger.warning('Failed adding %s as default gateway: %r', ipv4_gateway, e)
`logger.error` ?

2021-07-08 12:04 UTC, sonicaj approved these changes
Thanks

2021-07-08 12:05 UTC, merged