Core dumps on SCALE
truenas/middleware pull request #7142
Opened 2021-07-13 09:12 UTC by themylogin

2021-07-13 09:12 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111326

2021-07-13 11:04 UTC, anodos325 commented
The problem with simply removing the coredump files is that references to it will remain.
```
truenas# coredumpctl
TIME                            PID   UID   GID SIG COREFILE  EXE
Mon 2021-07-12 12:21:22 PDT  154313     0     0  11 missing   /usr/bin/sockstat
```

I think rather than removing coredumps, we should use one of the following config options for coredump.conf:
```
       MaxUse=, KeepFree=
           Enforce limits on the disk space taken up by externally stored core dumps.  MaxUse= makes sure that old core dumps are removed as soon as the total disk space taken up by core dumps grows beyond this limit (defaults to 10% of the total disk size).
           KeepFree= controls how much disk space to keep free at least (defaults to 15% of the total disk size). Note that the disk space used by core dumps might temporarily exceed these limits while core dumps are processed. Note that old core dumps are also
           removed based on time via systemd-tmpfiles(8). Set either value to 0 to turn off size-based clean-up.
```

2021-07-13 11:07 UTC, anodos325 commented
That said, the default 15% minimum free is probably good enough. In this case, then we can simply remove the code where we delete core files.

2021-07-13 11:11 UTC, anodos325 commented on src/middlewared/middlewared/alert/source/cores.py
> +            if os.stat(path).st_mtime < time.time() - 86400 * 5:
`coredumpctl --list` output contains a timestamp.

2021-07-13 11:22 UTC, anodos325 commented
For maximum scope-creep, maybe we could use a middleware plugin that wraps around `coredumpctl`. No ponies required... yet.

2021-07-26 17:28 UTC, rick-mesta commented
@anodos325: Has @themylogin properly addressed your concerns on this bad boy ? or are there additional deltas you'd like to see ?

2021-07-28 15:26 UTC, anodos325 commented
comments above still apply.

2021-07-28 15:28 UTC, themylogin commented
@anodos325 sorry, git push failed due to rebase

2021-07-28 15:31 UTC, yocalebo requested changes

2021-07-28 15:31 UTC, yocalebo commented on src/middlewared/middlewared/alert/source/cores.py
> +                corefiles.append(f"{coredump['exe']} ({coredump['time']})")
We need to ignore `syslog-ng` core dumps here as well. Someone else has already opened up a ticket for it core dumping on SCALE today. NAS-111566

2021-07-28 15:41 UTC, yocalebo approved these changes

2021-07-28 17:17 UTC, anodos325 approved these changes

2021-08-02 13:27 UTC, merged