dont reload webdav on post_import hook
truenas/middleware pull request #7184
Opened 2021-07-20 01:01 UTC by yocalebo

We call `service.reload <service>` for _all_ services on the system (whether they're enabled or not) after a zpool has been imported via the `post_import` hook.

To fix this, instead of going through the process of `etc.generate webdav`, we return early if there are no webdav shares configured on the system. This prevents the `apache2` daemon from being started when a zpool is imported.

2021-07-20 01:01 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111453

2021-07-22 13:33 UTC, rick-mesta approved these changes
LGTM: @anodos325 / @themylogin - would either/both of you guys also take a look ? 🙏🏼

2021-07-22 13:37 UTC, themylogin requested changes
So `service.reload` starts apache2 even if it was not started yet? Does this happen for all services of just for apache? Can we have a more explicit way of preventing this than just providing invalid configuration? (also why does apache not start when this file is not present? Is it included explicitly?)

2021-07-22 13:37 UTC, themylogin commented on src/middlewared/middlewared/etc_files/local/apache24/Includes/webdav.conf.mako
> +	apache_dir = service.APACHE_DIR.replace('local/', '')
Can we just change the original constant?

2021-07-22 13:42 UTC, yocalebo commented
> So `service.reload` starts apache2 even if it was not started yet?
Yes, the service is started since we create an empty `webdav.conf` file.

> Does this happen for all services of just for apache?
We were doing the same thing for proftpd in 11.3 but we also fixed it there. I've only looked at `apache2` service to see if it's the only one with this behavior.

> Can we have a more explicit way of preventing this than just providing invalid configuration?
I can change it so that the hook that gets called on pool import (`post_import`) for the webdav actually checks to see if there are any configured webdav shares and then `reload` it appropriately.

> (also why does apache not start when this file is not present? Is it included explicitly?)
See my first answer

2021-07-22 13:56 UTC, themylogin commented
@yocalebo won't it be cleaner to reload service only if it is enabled or started? Current code will start WebDAV if shares are present but service is disable which I believe is an incorrect behavior.

2021-07-27 20:13 UTC, closed without merging