add ability to enable/disable capabilities
truenas/middleware pull request #7243
Opened 2021-08-02 13:23 UTC by yocalebo

2021-08-02 13:23 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111544

2021-08-03 10:06 UTC, themylogin requested changes

2021-08-03 10:06 UTC, themylogin commented on src/middlewared/middlewared/plugins/interface/capabilities.py
> +        Str('action', enum=['enable', 'disable'], required=True),
All our enums should be uppercase

2021-08-03 10:06 UTC, themylogin commented on src/middlewared/middlewared/plugins/interface/capabilities.py
> +        return caps['enabled'] if data['enable'] else caps['disabled']
Is `data['enable']` a `KeyError`?

2021-08-03 13:46 UTC, themylogin approved these changes

2021-08-03 13:49 UTC, yocalebo commented
retest this please

2021-09-27 12:26 UTC, merged