fix numerous issues with disk.sync_all
truenas/middleware pull request #7282
Opened 2021-08-07 02:46 UTC by yocalebo

`disk.sync_all`, in my humble opinion, needs to be scrapped and rewritten. It's almost impossible to follow (at least for me) and it's terribly inefficient.

Problems discovered:
1. for each disk we called `geom.scan()` 3 times (maybe more)
2. after `geom.scan` we followed up that with a bunch of more `geom.*` module calls.
3. we subprocess'ed out for the enclosures for every disk
4. we then iterated over every enclosure's slot for every disk
5. we call `disk.query` multiple times per disk
6. we call `datastore.query storage.disk` multiple times per disk
7. `device.identifier_to_device` accepted a `disks` keyword, which as far as I can tell, was supposed to be used to "speed" that method up and yet, the keyword argument was completely ignored and overwritten when you called that method
8. `device.device_to_identifier` accepts a `disks` keyword as well, but it was never working because we ran `disk.get('nam')` instead of `disk.get(name)` (Notice the single-quotes around the `name` variable)

I really want to scrap it and rewrite it but alas time rules indiscriminately so here's what I've done to keep changes as minimal as possible.

1. stop calling geom.scan and geom* related api calls more than once for every disk. Instead call it once outside the for loop and pass it around to the various methods appropriately.
2. make the `device.identifier_to_device` accept said geom xml instantiation from a caller
3. fix `device.device_to_identifier` method to properly `.get(name)` so it's not a NO-OP
4. Nested deep down in `disk.identifier_to_device` there was a chance to crash on a `'NoneType' object has no attribute 'split'` so fix that while I'm here

Before my changes, on an M60 HA with 417 disks (and no other changes) `disk.sync_all` took ~6.5hrs....

After my changes, on an M60 HA with 417 disks `disk.sync_all` takes ~48 seconds

While I'm still not happy with 48 seconds, it will have to do for now.

2021-08-07 02:50 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111720

2021-08-07 18:24 UTC, themylogin requested changes

2021-08-07 18:24 UTC, themylogin commented on src/middlewared/middlewared/plugins/disk_/sync.py
> +            self.logger.info('Found disks: %r', log_info)
Can you log `Found 400 disks` in `else` branch please?

2021-08-07 18:24 UTC, themylogin commented on src/middlewared/middlewared/plugins/disk_/sync.py
> +        # now we need to check the enclosure mapping db info for each disk
Should we better have `sync_disks` method in enclosure plugin which will handle an array of disks in one place?

2021-08-08 17:15 UTC, themylogin approved these changes
Thank you!

2021-08-09 13:53 UTC, rick-mesta approved these changes

2021-08-09 13:55 UTC, merged