Move LDAP client code into explicit service plugin
truenas/middleware pull request #7329
Opened 2021-08-13 19:41 UTC by anodos325

This helps to standardize LDAP access and provides a somewhat
more abstract mechanism for interacting with remote LDAP servers
(if needed for AD plugin or other parts of middleware).

2021-08-13 19:41 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111838

2021-08-13 19:59 UTC, yocalebo requested changes
`_search` doesn't have `timeout` set which means this can block forever if the called method never returns.

2021-08-16 12:25 UTC, yocalebo approved these changes
My only concern is the main interpreter hanging during restart/shutdown if this thread is created and running before the timeout has elapsed.

Granted, it's probably not appropriate for you to solve that problem here since it requires adding some type of mechanism (threading event) that's shared between this ldap thread and parent thread. Anyways, other than that looks fine to me.

2021-08-16 12:28 UTC, yocalebo requested changes

2021-08-16 12:28 UTC, yocalebo commented on src/middlewared/middlewared/plugins/ldap.py
> +                    timeout=ldap_config['options']['timeout'],
Actually, wondering if we should make sure this is some sane value (instead of like 9999999).

2021-08-16 14:27 UTC, rick-mesta commented
@anodos325: ping -- is there any of @yocalebo 's comments that may require additional changes ?

2021-08-30 17:00 UTC, yocalebo approved these changes

2021-09-09 18:05 UTC, merged