Improvements to retrieving catalog(s)
truenas/middleware pull request #7336
Opened 2021-08-15 09:30 UTC by sonicaj

This PR adds following changes:

1) Do not automatically retrieve catalogs data. We should only do that in any of the following cases:

a) User explicitly went to Apps UI and requested to see the catalogs
b) User has configured catalogs which are not already builtin
c) User has configured kubernetes

2) Make sure that we always retrieve caching job if the catalog data is not readily available ( is not cached )

2021-08-15 09:30 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111852

2021-08-15 09:30 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111852

2021-08-16 12:20 UTC, yocalebo requested changes
This doesn't take into account if the end-user has checked the deny outbound network activity option in network general plugin.

2021-08-16 12:21 UTC, sonicaj commented
@yocalebo good point, i'll make required changes. Thanks for pointing it out

2021-08-19 11:13 UTC, yocalebo approved these changes

2021-08-19 11:31 UTC, merged