fix IoThreadPoolExecutor
truenas/middleware pull request #7367
Opened 2021-08-19 19:22 UTC by yocalebo

QE team and myself were able to reproduce python core dumps via the webUI. The reproduction case was convoluted and it's still unclear on why they're occurring. However, 1 thing is clear and it's being caused by our dynamic thread pool.

My change does a few things.

- derive our class from the upstream `ThreadPoolExecutor` class which unties us from the underlying implementation details
- instead of "shrinking" "idle" threads, we will simply spin-up single-use threads when all the threads in the threadpool are busy
- when the threadpool gets an idle thread, we'll go back to using the threadpool

2021-08-19 19:22 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111779

2021-08-20 10:46 UTC, themylogin commented
I am glad that it prevents crashes but then it's still a mystery how come that if we shut down a thread then we get a segfault, but when "disposable" `concurrent.futures.ThreadPoolExecutor(max_workers=1)` shuts down a thread everything it's fine. Have you tried crashing python when `self.run_in_thread_executor` is complete and every `run_in_thread` call spawns a new thread executor?

Should we also set constant `max_workers` for main thread pool executor?
```
Changed in version 3.8: Default value of max_workers is changed to min(32, os.cpu_count() + 4). This default value preserves at least 5 workers for I/O bound tasks. It utilizes at most 32 CPU cores for CPU bound tasks which release the GIL. And it avoids using very large resources implicitly on many-core machines.
```
And they'll change it again I am sure. We use this pool mostly for synchronous I/O, I doubt we should depend on CPU core count and get different I/O behavior on different machines.

2021-08-20 12:01 UTC, yocalebo commented
> I am glad that it prevents crashes but then it's still a mystery how come that if we shut down a thread then we get a segfault, but when "disposable" `concurrent.futures.ThreadPoolExecutor(max_workers=1)` shuts down a thread everything is fine.

There is a huge difference with how we implemented our thread pool compared to how upstream implemented it. For example, we use daemon threads, they do not. We use a `Queue`, they use a `SimpleQueue`. They use a `threading.Semaphore` object we do not. They use a global `weakref` object, we do not. Our implementation, when comparing to upstream, seems half-baked and not correct. I will admit, upstream has made changes to their implementation since we copied it but that's one of the main points on why I've made the change I've made here. It removes us from having to keep up with the implementation details since we don't have a complicated requirement (just need threads to be torn down).

> Have you tried crashing python when `self.run_in_thread_executor` is complete and every `run_in_thread` call spawns a new thread executor?
No I haven't. I'd be grateful if you know how to do this easily. I'll test it on my side no problem.

> Should we also set constant `max_workers` for main thread pool executor?
I went back and forth on this quite a bit. I will agree on one hand and say that I should probably default this to `20` like we had previously to maintain backwards functionality. However, we sell some large CPU count systems (m-series) so I'm wondering if we should use `32` when the cpu count is quite significant since, in theory, it will improve the performance of the API.

2021-08-20 12:07 UTC, themylogin commented
> I'd be grateful if you know how to do this easily. I'll test it on my side no problem.

Run some temporary method that will call `asyncio.ensure_future(self.middleware.run_in_thread(lambda: time.sleep(100000)))` 20 times

2021-08-20 12:08 UTC, themylogin commented
> However, we sell some large CPU count systems (m-series) so I'm wondering if we should use 32 when the cpu count is quite significant since, in theory, it will improve the performance of the API.

Agreed

2021-08-20 12:08 UTC, themylogin commented
backport

2021-08-20 12:08 UTC, yocalebo commented
> > I'd be grateful if you know how to do this easily. I'll test it on my side no problem.
> 
> Run some temporary method that will call `asyncio.ensure_future(self.middleware.run_in_thread(lambda: time.sleep(100000)))` 20 times

brilliant, thanks. I'll do that and test.

2021-08-20 14:29 UTC, themylogin requested changes

2021-08-20 14:29 UTC, themylogin commented on src/middlewared/middlewared/utils/io_thread_pool_executor.py
> +        return self._idle_semaphore._value - 1 == 1
Should it be `<= 1`?

2021-08-20 14:31 UTC, yocalebo commented on src/middlewared/middlewared/utils/io_thread_pool_executor.py
> +        return self._idle_semaphore._value - 1 == 1
good catch, it should

2021-08-20 14:34 UTC, themylogin approved these changes
LGTM. Do you want to also backport this to 21.08-BETA1?

2021-08-20 14:35 UTC, yocalebo commented
> LGTM. Do you want to also backport this to 21.08-BETA1?

Yeah I think we should. I'll add label

2021-08-20 16:44 UTC, merged