Fix ups reporting when running in slave mode
truenas/middleware pull request #7476
Opened 2021-09-03 16:33 UTC by sonicaj

This commit fixes an issue when we would not be showing reporting for UPS when it was running in slave mode because collectd stores ups logs in a different directory when it's running in slave mode.

2021-09-03 16:33 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-111856

2021-09-08 12:15 UTC, themylogin requested changes

2021-09-08 12:15 UTC, themylogin commented on src/middlewared/middlewared/plugins/reporting/plugins_freebsd.py
> +            self._base_path = os.path.join(RRD_BASE_DIR_PATH, ups_config['remotehost'])
Should we do this in the constructor instead?

Also RRDBase constructor has this
```
        self._base_path = RRD_BASE_PATH
        self.base_path = os.path.join(self._base_path, self.plugin)
```

Maybe we should just turn them into properties?

2021-09-13 13:25 UTC, rick-mesta commented
@themylogin: ping 🔔 - has @sonicaj's changes addressed your concern(s) ?

2021-09-14 16:38 UTC, themylogin approved these changes

2021-09-14 16:40 UTC, merged