make DiskStats not suck
truenas/middleware pull request #7611
Opened 2021-09-30 20:46 UTC by yocalebo

On an M60 with `1248` disks, these are the problems I've found:

1. The way we are calling `iostat` produces `2519` lines of text. We were parsing this every 2 seconds so we were parsing `5038` lines of text and discarding over half of it because we were calling `iostat` which included the `pass` devices.
2. we started a daemon thread that ran `subprocess` consistently to gather this information so we were having to read large output from child process which is painful
3. we were `0`'ing out the values for each disk and then summing them back together every 2 seconds....I honestly have no idea why we're doing it this way but it doesn't make any sense to me
4. every 2 seconds we were iterating over a `1248` key dictionary and cumulatively adding up the values for each disk in those 2 seconds

Here is how I've fixed these problems.

I've fixed these problems by doing a few things:
1. `psutils.disk_io_counters(perdisk=True, nowrap=True)` gives us the _exact_ same values as `iostat` and it even does the hard work of not wrapping the values so they never get reset to 0
2. get rid of the daemon thread
3. get rid of the child process that produces > 5k lines of text
4. no more absurd amount of text parsing

Before the changes, python had a thread that was eating 100% of a cpu core 100% of the time. Now it hardly shows in `top` output.

2021-09-30 20:46 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-112627

2021-09-30 20:48 UTC, anodos325 approved these changes

2021-09-30 21:03 UTC, themylogin approved these changes

2021-09-30 21:14 UTC, themylogin requested changes
Previous code was producing read/write ops/bytes count and disk busy time % for `reporting.realtime` interval (2 seconds). Current code produces total ops/bytes for the system lifetime.

2021-09-30 22:19 UTC, yocalebo commented
> Previous code was producing read/write ops/bytes count and disk busy time % for `reporting.realtime` interval (2 seconds). Current code produces total ops/bytes for the system lifetime.

Fixed the problem and also removed the `osc` related code to clean this up.

2021-09-30 22:41 UTC, themylogin requested changes
This code still provides read bytes count since system startup

Previous code was providing read bytes count in the last 2 seconds

2021-10-01 13:25 UTC, yocalebo commented
> This code still provides read bytes count since system startup
> 
> Previous code was providing read bytes count in the last 2 seconds

Subtle behavior that I didn't notice, thanks!

2021-10-01 13:44 UTC, themylogin approved these changes

2021-10-05 20:52 UTC, merged