Reduce noisy logs
truenas/middleware pull request #7928
Opened 2021-12-01 21:25 UTC by Qubad786

- Do not log exceptions from git cloning

2021-12-01 21:25 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113580

2021-12-02 10:08 UTC, sonicaj approved these changes

2021-12-02 12:47 UTC, yocalebo requested changes
I don't like the idea of storing another item in memory indefinitely while middlewared is running. This has potential for someone to abuse the API and fill up ram. (by specifying random URIs that never resolves). I would rather move these logs to a separate log file instead of having them in `middlewared.log`. We do this for `zettarepl` and `failover` already. Can we do something similar here?

2021-12-02 13:00 UTC, Qubad786 commented
@yocalebo can you please take another look? Its already not like how I told you in DM last night 😄  I am removing loggers and also tweaked log level for git client to CRITICAL so anything lower than that level would be skipped..

2021-12-02 13:02 UTC, yocalebo commented
> @yocalebo can you please take another look? Its already not like how I told you in DM last night 😄 I am removing loggers and also tweaked log level for git client to CRITICAL so anything lower than that level would be skipped..

oh wow, you're right. Sorry, I kept a browser tab opened up from yesterday and just looked at it this morning without refreshing. These changes look good!

2021-12-02 13:02 UTC, yocalebo approved these changes

2021-12-02 13:07 UTC, merged