Set ftp TimeoutNoTransfer
truenas/middleware pull request #7939
Opened 2021-12-06 16:40 UTC by themylogin

2021-12-06 16:40 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113041

2021-12-06 19:37 UTC, yocalebo requested changes
I don't like making `TimeoutIdle` = `TimeoutNoTransfer`. Especially for the original ticket creator that is using a `legacy backup application`. The man pages show that they're different options.  (They also don't do a good job of explaining the difference). Anyways, we already have a ton of ftp options in the webUI, so why not add another one?

2021-12-06 19:43 UTC, anodos325 commented
Maybe we can just allow `options` to override our hard-coded values.

2021-12-08 13:45 UTC, sonicaj approved these changes

2021-12-08 13:48 UTC, sonicaj reviewed
I agree with @yocalebo, i think it probably makes more sense to have another field ?

2021-12-10 13:29 UTC, closed without merging