Add validation to ensure that iso file can be consumed by libvirt
truenas/middleware pull request #8022
Opened 2021-12-19 15:43 UTC by sonicaj

2021-12-19 15:43 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113848

2021-12-19 16:56 UTC, yocalebo requested changes
I know this is WIP but we probably want to think about this a little more before we implement your solution.

I'd much rather resolve `username` to a uid and then use `os.stat` module (so we don't have to subprocess) and check the `st_uid` attribute for the given path and then `st_mode`.

Also, this only checks posix mode bits and not NFSv4 style acls so maybe we need to name the method a little more to what it's checking.

2021-12-20 13:41 UTC, yocalebo commented
Spoke to Waqar in chat and this change is fine for what's being accomplished but a new ticket will be opened up to rewrite the `run_command_with_user_context` (or maybe write an entirely different method to do something similar) that doesn't involve `subprocess` (since this is just trying to access path). 😄

2021-12-20 13:44 UTC, themylogin requested changes

2021-12-20 13:44 UTC, themylogin commented on src/middlewared/middlewared/plugins/filesystem_/perm_check.py
> +    def check_access_as_user(self, username, path, perms):
`can_access_as_user`

2021-12-20 15:51 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/vm_devices.py
> +                        os.chown(path, libvirt_user['uid'], libvirt_group['gid'])
So using an ISO file from a data storage will result in file's owner change?

2021-12-20 16:02 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/vm_devices.py
> +                        os.chown(path, libvirt_user['uid'], libvirt_group['gid'])
Do we need to continue with this behavior? Seems a little bit erratic.

2021-12-20 16:11 UTC, themylogin approved these changes

2021-12-20 16:21 UTC, merged