Add allow interfaces directive to avahi config
truenas/middleware pull request #8106
Opened 2022-01-06 21:35 UTC by anodos325

Deny interfaces will be interpreted before allow interfaces.
This will prevent avahi from registering veth and macvtap interfaces.

2022-01-06 21:35 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114187

2022-01-06 21:43 UTC, rick-mesta approved these changes

2022-01-07 13:52 UTC, yocalebo requested changes
Typo `middleare.call_sync`

I thought `macvtap` interfaces were in the `deny_interfaces` variable?

2022-01-07 14:30 UTC, anodos325 commented
> Typo `middleare.call_sync`
> 
> I thought `macvtap` interfaces were in the `deny_interfaces` variable?

`interface.internal_interfaces` returns `macvtap`, but not `macvtap0`, `macvtap1`, etc. Hence, it's not particularly useful in this case for the deny list.

2022-01-10 13:02 UTC, yocalebo approved these changes

2022-01-10 13:58 UTC, merged