Do not take snapshot of docker dataset when making a backup of apps
truenas/middleware pull request #8112
Opened 2022-01-10 05:36 UTC by sonicaj

Docker dataset is re-initialized from scratch as containers are ephemeral in kubernetes during restore. Docker zfs driver creates at least 1 dataset per layer in container/image if not more where we end up with a huge number of datasets. This change makes sure we do not take a snapshot of the docker dataset as we end up with potentially thousands of snapshots over time.

2022-01-10 05:36 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114223

2022-01-10 12:43 UTC, themylogin requested changes
This will be an inconsistent snapshot. Let me introduce an internal method to create recursive snapshots that exclude some of the datasets.

2022-01-10 12:55 UTC, themylogin commented
@sonicaj https://github.com/truenas/middleware/pull/8114

 `midclt call zettarepl.create_recursive_snapshot_with_exclude tank test-snapshot '["tank/.system"]'`

2022-01-11 12:36 UTC, themylogin approved these changes

2022-01-11 18:24 UTC, Ornias1993 approved these changes
Yeah, great cleanup!
Saves us a few thousand snapshots after a few backups :)

2022-01-12 06:51 UTC, merged