Explicitly restart/stop serial-getty service based on user specified settings
truenas/middleware pull request #8214
Opened 2022-02-06 19:11 UTC by sonicaj

2022-02-06 19:11 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114013

2022-02-07 20:05 UTC, themylogin requested changes
Nice!

Can we request test VM to have two serial ports and then try testing changing this value?

2022-02-07 20:05 UTC, themylogin commented on src/middlewared/middlewared/etc_files/ttys_config.py
> +from middlewared.utils import run
This does not generate any config files anymore, can we drop `ttys` pseudo-service and move it to a middleware plugin?

2022-02-07 20:05 UTC, themylogin commented on src/middlewared/middlewared/plugins/system.py
> +                    commands = [
Where is this variable used?

2022-02-08 04:59 UTC, sonicaj commented on src/middlewared/middlewared/plugins/system.py
> +                    commands = [
Which one ?

2022-02-08 09:49 UTC, themylogin commented on src/middlewared/middlewared/plugins/system.py
> +                    commands = [
`commands`

2022-02-08 20:05 UTC, themylogin requested changes

2022-02-08 21:55 UTC, themylogin approved these changes
Super cool, thank you!

2022-02-08 22:16 UTC, merged