Correctly validate disk device path
truenas/middleware pull request #8427
Opened 2022-03-03 19:05 UTC by Qubad786

2022-03-03 19:06 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-115001

2022-03-07 10:13 UTC, themylogin requested changes
This looks like a specific virtualization provider implementation detail. Why can't we just add this `+` when building the XML for libvirtd?

2022-03-08 12:45 UTC, sonicaj approved these changes

2022-03-08 12:46 UTC, sonicaj commented
@Qubad786 you have flake8 errors

2022-03-08 12:49 UTC, themylogin requested changes

2022-03-08 12:49 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/vm_devices.py
> +            vol['id']: os.path.join('/dev/zvol', vol['id'].replace(' ', '+'))
Shouldn't keys be the encoded value (with `+`) and values be human-readable value? Also let's use `zvol_name_to_path` here.

2022-03-08 15:04 UTC, merged