Correct vm disks path on SCALE
truenas/middleware pull request #8443
Opened 2022-03-04 17:57 UTC by Qubad786

Volumes are mounted as `/dev/zvol/vms/test 1` in freebsd but as `/dev/zvol/vms/test+1` in linux.

This PR adds:
1. An API to provide list of disks with correct zvol paths so UI can consume it as is unlike today (i.e. UI pre-fixes the `/dev/zvol` into volume name).
2. Add a migration for correcting existing vm disk devices for users who would be upgrading from CORE

PS: I have confirmed this behavior with @freqlabs on freebsd vs linux

2022-03-04 17:57 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-115001

2022-03-04 20:53 UTC, freqlabs commented
For context, this commit explains the udev rule: https://github.com/openzfs/zfs/commit/5f91bd3dea49a529e87e0aa39595f074fd09736a

2022-03-06 06:31 UTC, sonicaj commented on src/middlewared/middlewared/plugins/vm/vm_devices.py
> +    @returns(Dict())
Let's please add an `example` dict here

2022-03-06 06:31 UTC, sonicaj commented on src/middlewared/middlewared/plugins/vm/vm_devices.py
> +                'pool.dataset.query', [['type', '=', 'VOLUME']], {'extra': {'properties': []}}
Let's please also check if the volume is locked or not as we shouldn't be showing locked volume as a valid choice

2022-03-07 10:13 UTC, themylogin requested changes
This looks like a specific virtualization provider implementation detail. Why can't we just add this `+` when building the XML for libvirtd?

2022-03-07 10:38 UTC, Qubad786 commented
@themylogin its possible but in my opinion, we should make existing paths normalized in database and consume them dorectly instead of looking to add + everytime we get it from db.

2022-03-07 10:41 UTC, Qubad786 commented
Additionally, WebUI currently make this path on its side with space, I've delegated that to the middleware with choices API so it stays consistent.

2022-03-07 10:44 UTC, themylogin commented
@Qubad786 do you mean that `/dev/zvol/vms/test+1` is a normalized path, but `/dev/zvol/vms/test 1` is not?

2022-03-07 11:01 UTC, Qubad786 commented
`/dev/zvol/vms/test 1` is not correct path as zfs is mounting as `/dev/zvol/vms/test+1` in linux

2022-03-07 11:59 UTC, Qubad786 commented
Ah, thanks for pulling out, I'll address it!

2022-03-07 12:58 UTC, themylogin commented
@Qubad786 please take note of new utils implemented here https://github.com/truenas/middleware/pull/8452

2022-03-08 14:19 UTC, themylogin approved these changes

2022-03-08 14:52 UTC, rick-mesta approved these changes

2022-03-08 14:52 UTC, merged