Allow using min/max txg for querying snapshots
truenas/middleware pull request #8596
Opened 2022-03-20 19:22 UTC by sonicaj

2022-03-20 19:22 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-114497

2022-03-21 08:47 UTC, themylogin commented
Can we use `txg` to paginate a huge list of snapshots?

2022-03-21 11:54 UTC, themylogin approved these changes

2022-03-21 12:28 UTC, themylogin requested changes
Can we have an integration test please?

2022-03-21 12:29 UTC, sonicaj commented
Definitely

2022-03-29 11:53 UTC, yocalebo approved these changes

2022-03-29 12:00 UTC, merged