Allow moving system dataset to a passphrase-encrypted pool (system dataset will be unencrypted)
truenas/middleware pull request #8897
Opened 2022-05-07 11:09 UTC by themylogin

2022-05-07 11:10 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-113963

2022-05-07 11:11 UTC, themylogin commented
time 5:45

2022-05-07 16:39 UTC, pkgdemon commented
retest this please

2022-05-07 17:17 UTC, pkgdemon commented
retest this please

2022-05-07 17:27 UTC, themylogin commented
@pkgdemon are tests ran for the branch or for the branch merged/rebase on top of master? If the former then the test might fail in a weird way (middleware killing itself). I just rebased this branch on top of master, should not fail any more.

2022-05-10 15:58 UTC, sonicaj commented on src/middlewared/middlewared/plugins/sysdataset.py
> +        if new['pool'] == await self.middleware.call('boot.pool_name'):
Do we need this conditional ? I think `pool_choices` would still work nicely if the new configured pool is `boot-pool` ?

2022-05-11 11:01 UTC, sonicaj approved these changes

2022-05-11 11:04 UTC, yocalebo requested changes
Has this been tested on an HA system? We prevented encrypted system datasets from being used because of many factors.

2022-05-11 11:06 UTC, anodos325 commented
Has this been tested on server joined to AD?

2022-05-11 11:23 UTC, themylogin commented
> Has this been tested on an HA system? We prevented encrypted system datasets from being used because of many factors.

Currently we don't prevent encrypted system datasets from being used. Also this PR also does not introduce encrypted system dataset, it will have `encryption=off`

2022-05-11 11:25 UTC, themylogin commented
> Has this been tested on server joined to AD?

IIRC we don't allow changing system dataset is server is joined to AD, so I am not sure what should be tested?

2022-05-18 08:46 UTC, themylogin commented
@yocalebo @anodos325 ping

2022-05-31 21:44 UTC, themylogin commented
@anodos325 ping

2022-06-08 21:42 UTC, anodos325 approved these changes

2022-06-09 09:25 UTC, themylogin commented
@yocalebo ping

2022-06-23 10:41 UTC, themylogin commented
@yocalebo ping

2022-06-27 11:27 UTC, yocalebo approved these changes

2022-06-27 15:04 UTC, merged