NAS-116481 / 22.12 / Validate zfs resource names
truenas/middleware pull request #9070
Opened 2022-06-01 09:12 UTC by Qubad786

## Context

Right now when we create a zfs resource i.e pool/dataset/snapshot, we do not validate it's name and it errors out when we create the specific resource.

## Solution

Use py-libzfs for getting the validation which zfs performs to determine if the name in question is valid or not.

2022-06-01 09:13 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116481

2022-06-01 15:27 UTC, pkgdemon commented
retest this please

2022-06-01 16:14 UTC, anodos325 commented
> @anodos325 the methods are not using libzfs handle ?

Indeed they're not. Sorry, I was looking at `zfs_validate_name()` vs `zfs_name_valid()`.

2022-06-01 16:24 UTC, anodos325 commented
If we use `zfs_validate_name()` and `zpool_name_valid()` libzfs will print the exact reason for failure, but with the caveat I mentioned above about thread-safety.

2022-06-03 10:07 UTC, themylogin requested changes

2022-06-03 10:07 UTC, themylogin commented on src/middlewared/middlewared/plugins/zfs.py
> +            verrors.add('snapshot_create.name', 'Please specify a valid snapshot name')
Same note for error messages as before

2022-06-06 14:28 UTC, themylogin approved these changes

2022-06-06 21:29 UTC, merged