Refuse to download update if insufficient space avail
truenas/middleware pull request #9196
Opened 2022-06-10 14:18 UTC by anodos325

2022-06-10 14:19 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116678

2022-06-10 14:31 UTC, themylogin requested changes

2022-06-10 14:31 UTC, themylogin commented on src/middlewared/middlewared/plugins/update_/download.py
> +            avail = st.f_bavail * bsize
`filesystem.statfs` counts this as `'avail_bytes': st.f_bavail * st.f_frsize,`, why is it different here?

2022-06-10 14:31 UTC, themylogin commented on src/middlewared/middlewared/plugins/update_/download.py
> +            st = os.statvfs(os.path.dirname(dst))
`os.path.dirname(dst) == location`

2022-06-10 14:31 UTC, themylogin commented on src/middlewared/middlewared/plugins/update_/download.py
> +            if (1024**3) * 2 > avail:
Let's add `size` to https://update.freenas.org/scale/TrueNAS-SCALE-Angelfish/manifest.json (it is built by scale-build repo)

2022-06-24 11:00 UTC, anodos325 commented
This should not be merged until we get a successful build with the manifest changes and validate that it works correctly.

2022-09-28 13:31 UTC, yocalebo approved these changes

2022-09-28 13:33 UTC, merged