Snapshots based extents are not supported
truenas/middleware pull request #9478
Opened 2022-07-26 11:03 UTC by Qubad786

## Problem

ZFS snapshots based extents are not supported by SCST and it fails to start in that case.

```
[181259.053204] [1939741]: dev_vdisk: Registering virtual vdisk_blockio device extent3 (BLOCKIO)
[181259.055640] [1939741]: dev_vdisk: ***WARNING***: Device /dev/zvol/tank/extent3@1 doesn't support barriers, switching to NV_CACHE mode. Read README for more details.
[181259.058851] [1939741]: dev_vdisk: Auto enable thin provisioning for device /dev/zvol/tank/extent3@1
[181259.061443] [1939741]: dev_vdisk: Attached SCSI target virtual disk extent3 (file="/dev/zvol/tank/extent3@1", fs=10240MB, bs=512, nblocks=20971520, cyln=10240)
[181259.066089] [1939741]: scst: ***ERROR***: Device handler's vdisk_blockio attach_tgt() failed: -30
```

## Solution

Do not allow ZFS snapshots to be used as extents and add a migration disabling extents which are based on snapshot so that scst starts but the conflicting extents are disabled only.

2022-07-26 11:04 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-116482

2022-07-27 12:36 UTC, anodos325 commented on src/middlewared/middlewared/plugins/iscsi_/extents.py
>              [['attachment', '=', None]], {},
Add additional filter here `['ro', '=', False]` and skip the other refactoring.

2022-07-27 12:49 UTC, anodos325 commented on src/middlewared/middlewared/plugins/vm/vm_devices.py
> +            {}, ['ATTACHMENT', 'RO']
expand filter for `['ro', '=', False]`

2022-07-27 13:10 UTC, anodos325 commented
Since this is fixing some basic functionality / easing people migrating from Core, I think it should go into angelfish. 
@yocalebo thoughts?

This means we're probably doing the migration out of order, right? Need write migration for angelfish, then after merging that branch, cherry-pick for PR against master and create merge migration IIRC. Though I do this infrequently and tend to forget precise steps. @themylogin can give accurate guidance.

2022-07-27 13:12 UTC, yocalebo commented
Yeah, this should go into 22.0.2.4 to ease migration from core which means the alembic migration will need to be done in stable and then backported to master.

2022-07-27 13:13 UTC, yocalebo requested changes
Let's target this for 22.02.4 so we can ease migration from CORE to SCALE. Because of this, you'll need to make these changes in stable/angelfish repo first and the backport to master handling the alembic files accordingly. @themylogin can help in that respect if you have any questions.

2022-07-28 07:20 UTC, themylogin commented
@yocalebo I don't see any alembic migrations here, what do we want to do with alembic?

2022-07-28 09:34 UTC, anodos325 commented
> @yocalebo I don't see any alembic migrations here, what do we want to do with alembic?

The PR changed as investigation into the underlying issue proceeded. No more migration now.

2022-07-28 12:19 UTC, anodos325 commented on src/middlewared/middlewared/plugins/pool.py
> +        Inheritable(Str('snapdev', enum=['HIDDEN', 'VISIBLE']), has_default=False),
I wonder if we should default to `VISIBLE` on new zvol creation. If we do this though we may want to try creating 10K snapshots on a zvol and see whether anything breaks.

2022-07-28 12:42 UTC, themylogin approved these changes

2022-07-28 12:43 UTC, yocalebo approved these changes

2022-07-28 15:51 UTC, merged