Storj performance hints
truenas/middleware pull request #9885
Opened 2022-09-21 17:08 UTC by themylogin

2022-09-21 17:08 UTC, themylogin commented
time 0:10

2022-09-21 17:09 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-118198

2022-09-21 17:10 UTC, yocalebo requested changes
Can we have a docstring stating something like "Storj recommended these settings" or something similar so we know why we're doing this.

2022-09-21 17:56 UTC, yocalebo approved these changes

2022-09-21 17:57 UTC, merged

2022-10-10 16:53 UTC, yocalebo commented
backport