Persist cloud sync and rsync task state into the database and across …
truenas/middleware pull request #9886
Opened 2022-09-21 17:52 UTC by themylogin

…HA nodes

2022-09-21 17:53 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-111509

2022-09-21 18:21 UTC, themylogin commented
time 22:00

2022-09-22 16:22 UTC, yocalebo requested changes

2022-09-22 16:22 UTC, yocalebo commented on src/middlewared/middlewared/plugins/failover_/jobs_copy.py
> +            self.logger.exception("SUKA")
Don't think you meant to include this 😉

2022-09-22 16:47 UTC, themylogin commented on src/middlewared/middlewared/plugins/failover_/jobs_copy.py
> +            self.logger.exception("SUKA")
☠️

2022-10-27 16:25 UTC, yocalebo approved these changes

2022-10-27 16:25 UTC, merged