AUTO-71 / 22.12 / Adding API test cases to test system dataset
truenas/middleware pull request #9922
Opened 2022-09-28 15:00 UTC by ericbsd

2022-09-29 17:31 UTC, yocalebo requested changes

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +    assert results.json()['basename'] == 'encrypted/.system', results.textZ
```suggestion
    assert results.json()['basename'] == 'encrypted/.system', results.text
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_03_verify_the_first_pool_created_with_encrypted_root_dataset_become_the_system_dataset(request, pool_data):
```suggestion
def test_03_verify_sysds_is_moved_after_first_pool_is_created(request, pool_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_05_verify_logs_collection_still_work_after_enrcripted_dataset_is_moved_to_system_dataset(logs_data):
```suggestion
def test_05_verify_logs_after_sysds_is_moved_to_a_passphrase_encrypted_pool(logs_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_07_verify_logs_collection_still_work_after_enrcripted_dataset_is_deleted_still_work(logs_data):
```suggestion
def test_07_verify_logs_after_passphrase_encrypted_pool_is_deleted(logs_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_04_verify_the_system_dataset_can_move_to_an_encrypted_root_dataset(request):
```suggestion
def test_04_verify_sysds_can_move_to_a_passphrase_encrypted_pool(request):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_01_verify_system_dataset_is_set_to_boot_pool():
```suggestion
def test_01_verify_sysds_is_set_to_boot_pool():
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_06_delete_the_encrypted_pool_and_verify_the_system_dataset(request, pool_data):
```suggestion
def test_06_verify_sysds_after_passphrase_encrypted_pool_is_deleted(request, pool_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_08_creating_a_first_pool_and_verify_system_dataset_move_to_the_new_pool(request, pool_data):
```suggestion
def test_08_verify_sysds_moves_to_first_created_zpool(request, pool_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_09_creating_a_second_pool_and_verify_system_dataset_does_not_move_to_the_new_pool(request, pool_data):
```suggestion
def test_09_verify_sysds_does_not_move_after_second_pool_is_created(request, pool_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_10_verify_changing_a_system_dataset_is_impossible_while_AD_is_running(request):
```suggestion
def test_10_verify_changes_to_sysds_are_forbidden_while_AD_is_running(request):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_11_get_logs_before_moving_the_system_dataset_to_the_second_pool(logs_data):
```suggestion
def test_11_get_logs_before_moving_the_sysds_to_the_second_pool(logs_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_12_a_system_dataset_can_be_moved_to_second_pool_root_dataset(request):
```suggestion
def test_12_move_sysds_to_second_pool(request):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_13_verify_logs_collection_still_work_after_moving_the_system_dataset_to_the_second_pool(logs_data):
```suggestion
def test_13_verify_logs_after_sysds_is_moved_to_second_pool(logs_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_14_system_dataset_can_be_moved_to_another_pool_successfully_when_all_services_running(request):
```suggestion
def test_14_verify_sysds_can_be_moved_while_services_are_running(request):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_15_delete_the_second_pool_and_verify_the_system_dataset(request, pool_data):
```suggestion
def test_15_delete_second_pool_and_verify_sysds_is_moved_to_first_pool(request, pool_data):
```

2022-09-29 17:31 UTC, yocalebo commented on tests/api2/test_007_systemdataset.py
> +def test_16_delete_the_firs_pool_and_verify_the_system_dataset_moved_to_the_boot_pool(request, pool_data):
```suggestion
def test_16_delete_first_pool_and_verify_sysds_moved_to_the_boot_pool(request, pool_data):
```

2022-10-03 14:41 UTC, ericbsd commented
> Committed some of the changes but not all of them?

I missed some, but they should all be there now.

2022-10-03 15:38 UTC, yocalebo approved these changes

2022-10-03 15:48 UTC, merged